import test from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import fs from'node:fs';
import G from'../service/game-transfers.js';import BT from'../service/bittorrent.js';import Q from'../service/queue.js';import L from'../shared/core.js';
const collection={id:'fixture',url:'https://example.org/games.torrent',sourcePage:'https://example.org/',infoHash:'1'.repeat(40),checksum:'sha-256='+'2'.repeat(64),metadataBytes:2048,pieceLength:16384,total:65536,fileCount:4};
const a={id:'a',key:'ps1:first game',title:'First Game',platform:'ps1',collection:'fixture',files:[{index:2,path:'collection/First Game.bin',offset:16384,length:16384}]},b={id:'b',key:'ps1:second game',title:'Second Game',platform:'ps1',collection:'fixture',files:[{index:4,path:'collection/Second Game.bin',offset:49152,length:16384}]};
function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE transfer_jobs(id TEXT PRIMARY KEY,state TEXT,value TEXT,updated_at INTEGER);CREATE TABLE setup(key TEXT PRIMARY KEY,value TEXT);');const calls=[],states=new Map(),opts=new Map(),prepared=[],files=new Map();let now=1000;
 const client={ensureDir:async()=>{},available:async()=>1e12,rpc:async(method,args)=>{calls.push([method,args]);if(method==='getVersion')return{enabledFeatures:['BitTorrent']};if(method==='changeGlobalOption')return'OK';if(method==='addUri'){const o=args[1];states.set(o.gid,{status:'active',completedLength:'0'});opts.set(o.gid,o);return o.gid;}const s=states.get(args[0]);if(!s)throw Error('GID not found');if(method==='tellStatus')return s;if(method==='getOption')return opts.get(args[0]);if(method==='changeOption'){opts.set(args[0],{...opts.get(args[0]),...args[1]});return'OK';}if(method==='forcePause')s.status='paused';if(method==='unpause')s.status='active';if(method==='forceRemove')s.status='removed';if(method==='removeDownloadResult')states.delete(args[0]);return'OK';}};
 const options={sql:(q,p=[])=>({rows:db.prepare(q).all(...p)}),client,fs:(op,p)=>files.get(p)||{type:'directory'},catalog:{releases:[]},gameCatalog:{collections:{fixture:collection},games:[a,b]},gameQueue:{jobs:[],destination:()=>'/data/homebrew/PPSA99169/content/PS1',acceptTorrent:v=>prepared.push(v)},clock:()=>now};
 const manager=new G.GameTransfers(options);function metadata(j,changes={}){states.get(j.gid).status='complete';states.get(j.gid).completedLength='2048';states.get(j.gid).followedBy=['child-'+j.id];states.set('child-'+j.id,{status:'paused',infoHash:collection.infoHash,pieceLength:'16384',numPieces:'4',dir:j.destination,completedLength:'0',...changes});opts.set('child-'+j.id,{'select-file':'1-4'});}
 return{manager,options,states,opts,calls,files,prepared,metadata,db,time:t=>now=t};
}
const transportError=()=>Object.assign(Error('Local HTTP response timeout'),{rpcTransport:true});
test('slow partial pieces keep a torrent alive without inflating verified game progress',async()=>{const f=await payloadFixture(),{j}=f;f.time(124000);Object.assign(f.states.get(j.gid),{completedLength:'4096',downloadSpeed:'512',bitfield:'00'});await f.manager.tick();assert.equal(j.state,'downloading');assert.equal(j.received,0);assert.equal(j.lastProgress,124000);f.time(250000);f.states.get(j.gid).completedLength='8192';await f.manager.tick();assert.equal(j.state,'downloading');assert.equal(j.received,0);assert.equal(j.lastProgress,250000);f.db.close();});
test('lost payload with a surviving completed metadata receipt restarts with a fresh GID',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id),parent=j.gid;f.metadata(j);f.states.delete('child-'+j.id);j.state='error';await f.manager.action(j.id,'resume');await f.manager.tick();assert.equal(j.state,'metadata');assert.notEqual(j.gid,parent);assert.equal(f.states.has(parent),false);assert.equal(f.opts.get(j.gid)['select-file'],'2');assert.equal(j.pendingPayload,undefined);f.db.close();});
test('a stopped payload retry never reuses a completed metadata GID',async()=>{const f=await payloadFixture(),{j}=f;const child=j.gid;f.states.set(j.id,{status:'complete',completedLength:'2048',followedBy:[child]});Object.assign(f.states.get(child),{status:'error',errorCode:'7'});j.state='error';j.received=8000;await f.manager.action(j.id,'resume');await f.manager.tick();assert.equal(j.state,'metadata');assert.notEqual(j.gid,j.id);assert.notEqual(j.gid,child);assert.equal(j.received,8000);assert.equal(f.opts.get(j.gid)['select-file'],'2');f.db.close();});
async function payloadFixture(){const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);f.metadata(j);await f.manager.tick();return{...f,j};}
test('lost unpause response reconnects to the same payload without requeueing a collection',async()=>{const f=await payloadFixture(),{j}=f;await f.manager.action(j.id,'pause');await f.manager.action(j.id,'resume');const rpc=f.options.client.rpc;let once=true;f.options.client.rpc=async(m,a)=>{const r=await rpc(m,a);if(m==='unpause'&&once){once=false;throw transportError();}return r;};await f.manager.tick();const gid=j.gid;assert.equal(j.state,'queued');assert.equal(j.error,'');assert.equal(f.states.get(gid).status,'active');f.time(4000);await f.manager.tick();assert.equal(j.state,'downloading');assert.equal(j.gid,gid);assert.equal(f.opts.get(gid)['select-file'],'2');assert.equal(f.calls.filter(c=>c[0]==='addUri').length,1);f.db.close();});
test('temporary status RPC failure retains GID, partial progress and selected file',async()=>{const f=await payloadFixture(),{j}=f;j.received=8000;const gid=j.gid,rpc=f.options.client.rpc;let once=true;f.options.client.rpc=async(m,a)=>{if(m==='tellStatus'&&once){once=false;throw transportError();}return rpc(m,a);};await f.manager.tick();assert.equal(j.state,'queued');assert.equal(j.received,8000);assert.equal(j.gid,gid);assert.ok(!f.calls.some(c=>c[0]==='forcePause'));f.time(4000);await f.manager.tick();assert.equal(j.state,'downloading');assert.equal(j.gid,gid);assert.deepEqual(j.selected,[2]);f.db.close();});
test('lost addUri response is reconciled with its persisted requested GID',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true}),j=f.manager.find(d.id),rpc=f.options.client.rpc;let once=true;f.options.client.rpc=async(m,a)=>{const r=await rpc(m,a);if(m==='addUri'&&once){once=false;throw transportError();}return r;};await f.manager.tick();assert.equal(j.gid,j.id);assert.equal(j.state,'queued');f.time(4000);await f.manager.tick();assert.equal(j.state,'metadata');assert.equal(f.calls.filter(c=>c[0]==='addUri').length,1);f.db.close();});
test('failed selection RPC keeps metadata child paused until selection is verified',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);f.metadata(j);const rpc=f.options.client.rpc;let once=true;f.options.client.rpc=async(m,a)=>{if(m==='changeOption'&&once){once=false;throw transportError();}return rpc(m,a);};await f.manager.tick();assert.equal(j.state,'queued');assert.equal(f.states.get(j.pendingPayload).status,'paused');assert.ok(!f.calls.some(c=>c[0]==='unpause'));f.time(4000);await f.manager.tick();assert.equal(j.state,'downloading');assert.equal(f.opts.get(j.gid)['select-file'],'2');f.db.close();});
test('hash scanning is progress of verification, never bytes downloaded',async()=>{const f=await payloadFixture(),{j}=f;f.time(124000);Object.assign(f.states.get(j.gid),{verifiedLength:'32768',bitfield:'00'});await f.manager.tick();assert.equal(j.state,'downloading');assert.equal(j.verifying,true);assert.equal(j.received,0);assert.equal(j.lastProgress,124000);f.db.close();});
test('source checksum failure remains fatal and is not treated as a local timeout',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);Object.assign(f.states.get(j.gid),{status:'error',errorCode:'32',errorMessage:'HTTP failed'});await f.manager.tick();assert.equal(j.state,'error');assert.match(j.error,/checksum/);assert.equal(j.controlRetryAt,undefined);assert.ok(!f.calls.some(c=>c[0]==='unpause'));f.db.close();});
test('repeated local failures stop after a bounded retry budget and retain partial data',async()=>{const f=await payloadFixture(),{j}=f;const gid=j.gid;j.received=8000;const rpc=f.options.client.rpc;f.options.client.rpc=async(m,a)=>{if(m==='tellStatus')throw transportError();return rpc(m,a);};for(let i=0;i<7;i++){f.time(1000+i*21000);await f.manager.tick();}assert.equal(j.state,'error');assert.equal(j.gid,gid);assert.equal(j.received,8000);assert.equal(f.states.get(gid).status,'paused');f.db.close();});
test('pause cancels pending automatic recovery and resume revalidates file selection',async()=>{const f=await payloadFixture(),{j}=f;const rpc=f.options.client.rpc;let once=true;f.options.client.rpc=async(m,a)=>{if(m==='tellStatus'&&once){once=false;throw transportError();}return rpc(m,a);};await f.manager.tick();await f.manager.action(j.id,'pause');f.time(4000);await f.manager.tick();assert.equal(j.state,'paused');f.opts.get(j.gid)['select-file']='1-4';await f.manager.action(j.id,'resume');await f.manager.tick();assert.equal(j.state,'error');assert.match(j.error,/selection/);assert.equal(f.states.get(j.gid).status,'paused');f.db.close();});
test('RPC errors distinguish unavailable local transport from an engine rejection',async()=>{const cfg={wfm:'http://127.0.0.1:8888',aria:'http://127.0.0.1:6800'};const unavailable=new L.Client(cfg,async()=>{throw Error('HTTP failed');});await assert.rejects(()=>unavailable.rpc('unpause',['gid']),e=>e.rpcTransport===true&&e.rpcMethod==='unpause');const rejected=new L.Client(cfg,async()=>({ok:true,status:200,json:async()=>({error:{code:1,message:'GID not found'}})}));await assert.rejects(()=>rejected.rpc('tellStatus',['gid']),e=>e.rpcTransport===false&&e.message==='GID not found');});
test('game card queues only its files and checks upload consent before network contact',async()=>{const f=fixture();await f.manager.init();await assert.rejects(()=>f.manager.addGame('a'),/notice/);assert.ok(!f.calls.some(c=>c[0]==='addUri'));const d=await f.manager.addGame('a',{uploadAccepted:true});assert.equal(d.fileCount,1);assert.deepEqual(d.files.map(x=>x.index),[2]);assert.equal(d.selectionLocked,true);await f.manager.tick();const request=f.calls.find(c=>c[0]==='addUri')[1];assert.equal(request[1]['pause-metadata'],'true');assert.equal(request[1]['select-file'],'2');assert.equal(request[1].checksum,collection.checksum);f.db.close();});
test('metadata children remain paused until infohash and selected indices are verified',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);f.metadata(j);await f.manager.tick();assert.equal(j.stage,'payload');assert.equal(f.opts.get(j.gid)['select-file'],'2');const verify=f.calls.findIndex(c=>c[0]==='getOption'),unpause=f.calls.findIndex(c=>c[0]==='unpause');assert.ok(verify>=0&&unpause>verify);assert.equal(f.states.get(j.gid).status,'active');f.db.close();});
test('changed collection hash cannot start payload or select another game',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);f.metadata(j,{infoHash:'9'.repeat(40)});await f.manager.tick();assert.equal(j.state,'error');assert.ok(!f.calls.some(c=>c[0]==='unpause'));assert.equal(f.states.get(j.pendingPayload).status,'paused');f.db.close();});
test('progress uses byte offsets in the collection and only the selected file is prepared',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);f.metadata(j);await f.manager.tick();const s=f.states.get(j.gid);Object.assign(s,{status:'complete',bitfield:'40'});f.files.set(j.destination+'/'+a.files[0].path,{type:'file',size:16384});await f.manager.tick();assert.equal(j.received,16384);assert.equal(j.state,'complete');assert.equal(f.prepared.length,1);assert.deepEqual(f.prepared[0].inputs.map(x=>x.name),['First Game.bin']);assert.ok(!f.states.has(j.gid));f.db.close();});
test('different games in one collection are separate jobs and serialize while a payload is held',async()=>{const f=fixture();await f.manager.init();const first=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const second=await f.manager.addGame('b',{uploadAccepted:true});await f.manager.tick();assert.equal(f.manager.find(second.id).state,'queued');assert.equal(f.manager.find(second.id).waitingForCollection,true);await f.manager.action(first.id,'cancel');await f.manager.tick();assert.equal(f.manager.find(second.id).state,'metadata');f.db.close();});
test('cancelling a metadata job removes its paused child and never unpauses it',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const j=f.manager.find(d.id);f.metadata(j);await f.manager.action(j.id,'cancel');assert.equal(j.state,'canceled');assert.ok(!f.states.has('child-'+j.id));assert.ok(!f.calls.some(c=>c[0]==='unpause'));f.db.close();});
test('game restart preserves file selection and destination without automatic downloads',async()=>{const f=fixture();await f.manager.init();const d=await f.manager.addGame('a',{uploadAccepted:true});await f.manager.tick();const recovered=new G.GameTransfers(f.options);await recovered.init();const j=recovered.find(d.id);assert.equal(j.state,'paused');assert.deepEqual(j.selected,[2]);assert.equal(j.gameDestination,'/data/homebrew/PPSA99169/content/PS1');f.db.close();});
test('indexed file selections reject traversal and invalid ranges',()=>{assert.deepEqual(G.selection('2,4-6'),[2,4,5,6]);for(const s of['','0','1-9999','all'])assert.throws(()=>G.selection(s));for(const patch of[{path:'collection/../evil.bin'},{index:0},{offset:-1},{length:1e15}])assert.throws(()=>G.validateRelease({...a,files:[{...a.files[0],...patch}]},collection));});
test('large PS3 and Xbox 360 pieces preserve exact selected-byte accounting',()=>{const size=64*1048576,c={...collection,pieceLength:size,total:size*5};const game={...a,platform:'ps3',files:[{index:2,path:'Collection/One Game.zip',offset:size-10,length:size+20}]};assert.doesNotThrow(()=>G.validateRelease(game,c));assert.equal(BT.completed(game.files,[2],size,'e0'),size+20);assert.equal(BT.completed(game.files,[2],size,'80'),10);assert.throws(()=>G.validateRelease(game,{...c,pieceLength:128*1048576}));});
test('PS3, Switch and both Xbox categories have actual per-game torrent selections',()=>{const cards=JSON.parse(fs.readFileSync(new URL('../assets/catalog.json',import.meta.url))),data=JSON.parse(fs.readFileSync(new URL('../assets/game-torrents.json',import.meta.url)));for(const p of ['ps3','switch','xbox','xbox360']){assert.ok(cards.some(c=>c.platform===p&&c.options.some(o=>o.method==='torrent')),p);const games=data.games.filter(g=>g.platform===p);assert.ok(games.length);for(const g of games){G.validateRelease(g,data.collections[g.collection]);if(p==='switch'){assert.ok(g.files.every(f=>/\.nsp$/i.test(f.path)));assert.ok(g.files.every(f=>!/\bDLC\b|\[Update/i.test(f.path)));if(g.titleId)assert.ok(g.titleId.endsWith('000'));}}}});
test('PS3 and original Xbox torrent variants retain verified emulator disc formats',()=>{const data=JSON.parse(fs.readFileSync(new URL('../assets/game-torrents.json',import.meta.url)));assert.ok(!data.collections['ps3-redump']);assert.ok(!data.collections['xbox-redump']);for(const g of data.games.filter(g=>['ps3','xbox'].includes(g.platform))){assert.equal(g.files.length,1);assert.equal(g.sourceCheck.header,true);if(g.platform==='ps3'){assert.equal(g.sourceCheck.psfVerified,true);assert.equal(g.sourceCheck.ebootVerified,true);}else assert.equal(g.sourceCheck.partitionOffset,0);}});
test('catalog retains direct sources and exposes actual per-game torrent options under PS1 and PS2',()=>{const cards=JSON.parse(fs.readFileSync(new URL('../assets/catalog.json',import.meta.url))),data=JSON.parse(fs.readFileSync(new URL('../assets/game-torrents.json',import.meta.url)));const byId=new Map(data.games.map(g=>[g.id,g]));assert.ok(cards.filter(c=>c.platform==='ps1'&&c.options.length).length>7500);assert.ok(cards.filter(c=>c.platform==='ps2'&&c.options.length).length>7500);const ids=new Set();for(const c of cards){assert.ok(!ids.has(c.key));ids.add(c.key);for(const o of c.options.filter(o=>o.method==='torrent')){const g=byId.get(o.id);assert.equal(g.key,c.key);G.validateRelease(g,data.collections[g.collection]);}}assert.ok(cards.some(c=>c.options.some(o=>o.method!=='torrent')));assert.ok(data.games.some(g=>g.files.length>1));const bond=data.games.find(g=>g.collection==='ps1-chd'&&g.files.some(f=>f.path.endsWith('/007 - The World Is Not Enough (USA).chd')));assert.equal(bond.files[0].index,1809);assert.equal(bond.files[0].length,413158372);});
test('preparation scans selected input files, never unselected boundary files',async()=>{const prepared=[];const client={wfm:'http://127.0.0.1:8888',rpcURL:'http://127.0.0.1:6800/jsonrpc',add:async()=>{throw Error('Already downloaded');},rpc:async()=>{},list:async()=>prepared.length?[{name:'First Game.chd',type:'-',size:2352*10}]:[],scan:async()=>{throw Error('Whole collection must not be scanned');},bytes:async()=>new Uint8Array(Buffer.from('MComprHD000000000')),api:async(route,v)=>{if(route==='move'){prepared.push(v.paths);return{task_id:'m'};}if(route==='tasks')return{tasks:[{id:'m',op:'move',src:prepared[0],dst:'/data/homebrew/PPSA99169/content/PS1/First Game.chd',state:'done'}]};},available:async()=>1e12};const q=new Q.Queue({catalog:{games:[]},read:()=>'',write:()=>{},clientFactory:()=>client});const j=q.acceptTorrent({id:'123',key:a.key,title:a.title,platform:'ps1',optionId:'a',dir:L.platformFor('ps1').staging+'/123',destination:'/data/homebrew/PPSA99169/content/PS1',inputs:[{name:'First Game.chd',path:L.platformFor('ps1').staging+'/123/collection/First Game.chd',size:2352*10}],total:2352*10});assert.equal(j.inputs.length,1);assert.equal(j.phase,'scan');assert.equal(q.acceptTorrent({id:'123'}),undefined);assert.equal(q.jobs.length,1);await q.engines.get(j.id).resume();assert.equal(j.phase,'done');assert.deepEqual(prepared,[j.inputs[0].path]);});
