import test from 'node:test';import assert from 'node:assert/strict';import L from '../shared/core.js';import I from '../shared/identity.js';import{createRequire}from'node:module';const require=createRequire(import.meta.url),{Queue}=require('../service/queue.js');
const game={id:'ps4:test',title:'Test',platform:'ps4',titleId:'CUSA12345',url:'https://example.org/CUSA12345-Test.pkg',filename:'CUSA12345-Test.pkg',sizeBytes:1024};
test('native PS5 FIH package validates bounded segments and rejects truncated or unsafe offsets',()=>{const bytes=new Uint8Array(4096),v=new DataView(bytes.buffer);v.setUint32(0,0x7f464948,false);v.setUint32(0x10,65536,true);v.setUint32(0x18,65536,true);v.setUint32(0x58,131072,true);v.setUint32(0xa0,8192,true);assert.equal(L.verifyHeader('PS5.pkg',bytes,140000),true);assert.throws(()=>L.verifyHeader('PS5.pkg',bytes,131073));assert.throws(()=>L.verifyHeader('PS5.pkg',bytes.subarray(0,128),140000));v.setUint32(0x58,70000,true);assert.throws(()=>L.verifyHeader('PS5.pkg',bytes,140000));v.setUint32(0x5c,0xffffffff,true);assert.throws(()=>L.verifyHeader('PS5.pkg',bytes,1e18));});
test('package URL brackets are encoded without changing the filename or query',()=>{const g=L.validateGame({...game,url:'https://archive.org/download/test/Game%20[EU].pkg?x=1'});assert.equal(g.url,'https://archive.org/download/test/Game%20%5BEU%5D.pkg?x=1');assert.equal(g.filename,game.filename);});
test('PS4 and PS5 packages validate without being confused with UFS images',()=>{const bytes=new Uint8Array(512);new DataView(bytes.buffer).setUint32(0,0x7f434e54,false);for(const platform of ['ps4','ps5'])for(const ext of ['pkg','fpkg']){assert.equal(L.validateGame({...game,platform,filename:'Test.'+ext}).platform,platform);assert.equal(L.verifyHeader('Test.'+ext,bytes,1024),true);}assert.throws(()=>L.verifyHeader('Test.ffpkg',bytes,1024));assert.throws(()=>L.verifyHeader('Test.pkg',new TextEncoder().encode('<html>Login</html>'),1024));assert.throws(()=>L.verifyHeader('Test.pkg',bytes.subarray(0,10),1024));assert.equal(I.sameInstalled(game,{name:'PPSA12345-Test.pkg'}),false);});
test('custom destination rejects traversal, application folders and unbound system roots',()=>{assert.equal(L.destinationPath('/data/my games/PS4/'),'/data/my games/PS4');assert.equal(L.destinationPath('/mnt/usb0/Games/PS4'),'/mnt/usb0/Games/PS4');for(const p of ['/user/app','/app0/assets','/data/games/../homebrew','/data/homebrew/x','/data/raff/native-v5','/data/PCSX2/.ps2-library/x','/mnt/usb9/games','/mnt/usb0','/data','/data/games\n','/data/games\\evil'])assert.throws(()=>L.destinationPath(p));});
function queue(){let storage={},created=[];const c={rpc:async()=>({}),ensureDir:async p=>created.push(p),list:async p=>{if(p==='/data/PCSX2/games')return[{name:'Game.chd',path:p+'/Game.chd',type:'-'}];if(p==='/data/etaHEN/games')return[];if(p==='/mnt')return[];throw Error('not found');}};const q=new Queue({catalog:{games:[game]},read:n=>storage[n],write:(n,v)=>storage[n]=v,clientFactory:()=>c});return{q,storage,created};}
test('RetroArch destination allows only its content tree within homebrew',()=>{
 const content='/data/homebrew/PPSA99169/content';
 for(const p of [content,content+'/PS1',content+'/My Games/PS1'])assert.equal(L.destinationPath(p+'/'),p);
 for(const p of [content+'-other',content+'x',content+'/../cores',content+'/./PS1',content+'/PS1/../../cores','/data/homebrew/PPSA99169/cores','/data/homebrew/PPSA99178/content'])assert.throws(()=>L.destinationPath(p),p);
});
test('new PS1 jobs use RetroArch content while existing jobs retain their destination',async()=>{
 const {q,created}=queue(),content='/data/homebrew/PPSA99169/content/PS1';
 const first={id:'ps1:path-first',title:'First',platform:'ps1',url:'https://example.org/First.chd',filename:'First.chd',sizeBytes:1024};
 const second={...first,id:'ps1:path-second',title:'Second',filename:'Second.chd',url:'https://example.org/Second.chd'};
 q.catalog.games.push(first,second);await q.init();
 assert.equal(q.destination(first),content);
 await q.configure({paths:{ps1:'/data/RetroArch/roms/ps1'}});q.add(first.id);
 await q.configure({paths:{ps1:content}});q.add(second.id);
 assert.ok(created.includes(content));
 assert.equal(q.jobs[0].game.destination,'/data/RetroArch/roms/ps1');
 assert.equal(q.jobs[1].game.destination,content);
 assert.equal(q.settings.paths.ps1,content);
});
test('game destination is snapshotted and per-game override takes priority over platform',async()=>{const{q,created}=queue();await q.init();await q.configure({paths:{ps4:'/data/PS4'}});await q.configure({gamePath:{key:I.identity(game),path:'/data/favorites/Test'}});q.add(game.id);assert.equal(q.jobs[0].game.destination,'/data/favorites/Test');await q.configure({gamePath:{key:I.identity(game),path:'/mnt/usb0/Games'}});assert.equal(q.jobs[0].game.destination,'/data/favorites/Test');assert.equal(q.destination(game),'/mnt/usb0/Games');assert.ok(created.includes('/data/favorites/Test'));await assert.rejects(()=>q.configure({gamePath:{key:I.identity(game),path:'/user/app'}}));});
test('automatic folder scan keeps explicitly selected paths and reports existing candidates',async()=>{const{q}=queue();await q.init();await q.configure({paths:{ps2:'/data/custom'}});await q.scanPaths();assert.equal(q.settings.paths.ps2,'/data/custom');assert.equal(q.pathScan.results.ps2.path,'/data/PCSX2/games');assert.equal(q.pathScan.results.ps2.found,true);assert.equal(q.pathScan.running,false);});
test('USB destination is not manufactured when the drive is absent',async()=>{const c=new L.Client({wfm:'http://example.org',aria:'http://example.org'});c.list=async()=>[];c.api=async()=>{throw Error('must not create');};await assert.rejects(()=>c.ensureDir('/mnt/usb0/Games'),/USB/);});
test('classic download connection preference preserves resumable files',async()=>{const c=new L.Client({wfm:'http://example.org',aria:'http://example.org'});let call;c.rpc=async(method,args)=>{call={method,args};return'gid';};await c.add(game.url,'/data/raff/ps4-staging/job','Test.pkg','gid');const options=call.args[1];assert.equal(options.split,'16');assert.equal(options['max-connection-per-server'],'16');assert.equal(options['min-split-size'],'1M');assert.equal(options.continue,'true');assert.equal(options['allow-overwrite'],'false');});
test('verified package moves to the selected custom folder and never invokes an installer',async()=>{const destination='/data/My PS4 Games',entries=[],calls=[],header=new Uint8Array(512);new DataView(header.buffer).setUint32(0,0x7f434e54,false);let expected,task;const c={wfm:'http://console:8888',rpcURL:'http://console:6800/jsonrpc',ensureDir:async()=>{},available:async()=>1e12,list:async path=>path===destination?entries:[],bytes:async()=>header,add:async(url,dir,name)=>{expected=dir+'/'+name;},rpc:async method=>{assert.equal(method,'tellStatus');return{status:'complete',completedLength:'1024',totalLength:'1024',files:[{path:expected}]};},scan:async dir=>[{name:game.filename,path:dir+'/'+game.filename,type:'-',size:1024}],api:async(route,v)=>{calls.push(route);if(route==='move'){assert.equal(v.dst,destination);assert.equal(v.overwrite,'0');task={id:1,op:'move',src:v.paths,dst:destination+'/'+game.filename,state:'done'};entries.push({name:game.filename,path:task.dst,type:'-',size:1024});return{task_id:1};}assert.equal(route,'tasks');return{tasks:[task]};}};const engine=new L.Engine(c,()=>{});await engine.begin({...game,destination});assert.equal(engine.job.phase,'done');assert.deepEqual(engine.job.moved,[destination+'/'+game.filename]);assert.deepEqual(calls,['move','tasks']);});
