import test from'node:test';import assert from'node:assert/strict';import queueModule from'../service/queue.js';import lib from'../shared/core.js';
const{Queue,FileGate}=queueModule;
const game=(title,extra={})=>({id:title,title,platform:'ps2',url:'https://example.org/'+encodeURIComponent(title)+'.chd',filename:title+'.chd',sizeBytes:1024,...extra});
function setup(games,options={}){let saved={},states=new Map(),dest=[],active=0,max=0,taskId=0,task=null;const gateEvents=[];
 class Fake extends lib.Client{constructor(){super({wfm:'http://127.0.0.1:8888',aria:'http://127.0.0.1:6800'});}async ensureDir(){}async available(){return options.free??10e12;}async add(url,dir,name,gid){states.set(gid,{name,path:dir+'/'+name,status:'active'});active++;max=Math.max(max,active);}async list(path){return path===lib.GAMES?dest:[];}async bytes(){let b=new Uint8Array(128);b.set(new TextEncoder().encode('MComprHD'));return b;}async scan(path){let s=[...states.values()].find(x=>x.path.startsWith(path));return[{name:s.name,path:s.path,type:'-',size:1024}];}async rpc(method,args){if(method==='changeGlobalOption'||method==='getVersion')return{};let s=states.get(args[0]);if(method==='pause'){s.status='paused';return'OK';}if(method==='unpause'){s.status='active';return'OK';}if(method==='remove'){s.status='removed';return'OK';}if(method==='tellStatus')return{status:s.status,totalLength:'1024',completedLength:s.status==='complete'?'1024':'512',downloadSpeed:'128',files:[{path:s.path}]};throw Error(method);}async api(route,v){if(route==='move'){assert.ok(!task,'File operations overlap');task={id:++taskId,op:'move',src:v.paths,dst:v.dst+'/'+v.paths.split('/').pop(),state:'done'};dest.push({name:v.paths.split('/').pop(),path:task.dst,type:'-',size:1024});gateEvents.push(v.paths);return{task_id:taskId};}if(route==='tasks'){const t=task;task=null;return{tasks:[t]};}throw Error(route);}}
 const q=new Queue({catalog:{games},read:n=>saved[n],write:(n,v)=>saved[n]=v,clientFactory:()=>new Fake(),clock:options.clock});return{q,states,dest,saved,max:()=>max,events:gateEvents,complete(){for(const s of states.values())s.status='complete';active=0;}};}
test('three games download concurrently, a fourth waits, then verified moves serialize',async()=>{const f=setup(['Alpha','Beta','Gamma','Delta'].map(t=>game(t)));await f.q.init();for(const g of f.q.catalog.games)f.q.add(g.id);await f.q.pump();await new Promise(r=>setTimeout(r,20));assert.equal(f.states.size,3);assert.equal(f.q.jobs[3].phase,'queued');assert.equal(f.max(),3);f.complete();await new Promise(r=>setTimeout(r,950));assert.equal(f.q.jobs.filter(j=>j.phase==='done').length,3);assert.equal(f.events.length,3);await f.q.pump();await new Promise(r=>setTimeout(r,20));f.complete();await new Promise(r=>setTimeout(r,950));assert.equal(f.q.jobs[3].phase,'done');});
test('a region mirror is blocked in queue and against an installed ISO',async()=>{const f=setup([game('Racer (USA)'),game('Racer (Europe)')]);await f.q.init();f.q.add('Racer (USA)');assert.throws(()=>f.q.add('Racer (Europe)'),/Already queued/);f.q.jobs=[];f.q.installed.ps2=[{name:'Racer (Japan).iso'}];assert.throws(()=>f.q.add('Racer (Europe)'),/Already installed/);});
test('ETA uses measured rate, is unknown when stopped, and settings are bounded',async()=>{let now=0;const f=setup([game('A')],{clock:()=>now});await f.q.init();const j={phase:'downloading',total:1000,received:200,speed:100};f.q.update(j);assert.equal(j.eta,8);j.received=400;j.speed=0;j.phase='extracting';f.q.update(j);assert.equal(j.eta,null);await f.q.configure({parallel:100,connections:100});assert.equal(f.q.settings.parallel,4);assert.equal(f.q.settings.connections,16);});
test('queued pause and cancel are persistent and do not start network traffic',async()=>{const f=setup([game('A')]);await f.q.init();const{id}=f.q.add('A');await f.q.action(id,'pause');await f.q.pump();assert.equal(f.states.size,0);assert.equal(JSON.parse(f.saved.jobs)[0].paused,true);await f.q.action(id,'cancel');assert.equal(f.q.jobs[0].phase,'canceled');});
test('space reservation accounts for other queued games',async()=>{const f=setup([game('A',{sizeBytes:300*1048576}),game('B',{sizeBytes:300*1048576})],{free:700*1048576});await f.q.init();f.q.add('A');f.q.add('B');await f.q.pump();await new Promise(r=>setTimeout(r,20));assert.equal(f.states.size,0);assert.ok(f.q.jobs.every(j=>j.error));});
test('file gate holds other jobs until extract/move transaction releases',async()=>{const gate=new FileGate(),events=[];await gate.call('A',async()=>events.push('extract'),true);let waiting=gate.call('B',async()=>events.push('list'));await Promise.resolve();assert.deepEqual(events,['extract']);await gate.call('A',async()=>events.push('verified'));gate.release('A');await waiting;assert.deepEqual(events,['extract','verified','list']);});

test('live progress stays fractional and uses received bytes, including files over 4 GiB',async()=>{let now=10;const f=setup([game('Large',{sizeBytes:20e9})],{clock:()=>now});await f.q.init();const{id}=f.q.add('Large'),j=f.q.jobs.find(j=>j.id===id);Object.assign(j,{phase:'downloading',received:5e9,total:20e9,progress:0,speed:25e6});let status=f.q.status();assert.equal(status.jobs[0].progress,.25);j.received=12e9;now=11;status=f.q.status();assert.equal(status.jobs[0].progress,.6);assert.equal(status.updatedAt,11);j.phase='done';assert.equal(f.q.status().jobs[0].progress,1);});
