import test from'node:test';import assert from'node:assert/strict';import L from'../shared/core.js';import Q from'../service/queue.js';
const game={id:'one',platform:'ps4',title:'One',titleId:'CUSA12345',filename:'One.pkg',sizeBytes:8192,url:'https://ia601509.us.archive.org/5/items/test/One.pkg',mirrors:['https://ia801509.us.archive.org/5/items/test/One.pkg']};
test('failed download retries on new GID with same partial file and all mirrors',async()=>{
 const calls=[],j={id:'one',game,dir:'/data/raff/ps4-staging/one',gid:'old',phase:'downloading',endpoint:'http://console:8888',rpcURL:'http://console:6800/jsonrpc',moved:[],received:4096};let engine;
 const c={wfm:j.endpoint,rpcURL:j.rpcURL,rpc:async(m,a)=>{calls.push([m,a]);if(m==='removeDownloadResult')return'OK';return a[0]==='old'?{status:'error',files:[{path:j.dir+'/One.pkg'}]}:{status:'complete',totalLength:'8192',completedLength:'8192',files:[{path:j.dir+'/One.pkg'}]};},add:async(...a)=>calls.push(['add',a])};
 engine=new L.Engine(c,()=>{if(j.phase==='scan')engine.stopRequested=true;});engine.job=j;await engine.resume();assert.notEqual(j.gid,'old');assert.equal(j.phase,'scan');assert.equal(j.received,8192);assert.deepEqual(calls.find(x=>x[0]==='add')[1],[game.url,j.dir,game.filename,j.gid,undefined,game.mirrors]);assert.equal(calls.filter(x=>x[0]==='removeDownloadResult').length,1);
});
test('unverified mirrors are excluded and partial files are preserved',async()=>{const c=new L.Client({wfm:'http://console',aria:'http://console'});c.rpc=async(m,a)=>{assert.equal(m,'addUri');assert.deepEqual(a[0],[game.url]);assert.equal(a[1].continue,'true');assert.equal(a[1]['allow-overwrite'],'false');};await c.add(game.url,'/data/raff/ps4-staging/job',game.filename,'gid',undefined,game.mirrors);});
test('installation preferences are snapshotted and actual installed title blocks re-download',async()=>{const c={rpc:async()=>({}),list:async()=>[],ensureDir:async()=>{}};const q=new Q.Queue({catalog:{games:[game]},read:()=>'',write:()=>{},clientFactory:()=>c});await q.init();assert.equal(q.settings.autoInstall,false);await q.configure({autoInstall:true,removePackages:true});q.add(game.id);assert.deepEqual(q.jobs[0].installOptions,{enabled:true,remove:true});await q.configure({autoInstall:false,removePackages:false});assert.deepEqual(q.jobs[0].installOptions,{enabled:true,remove:true});q.jobs=[];q.add(game.id);assert.deepEqual(q.jobs[0].installOptions,{enabled:false,remove:false});q.jobs=[];q.systemTitleIds=[game.titleId];assert.throws(()=>q.add(game.id),/Already installed/);assert.equal(q.status().installedKeys.length,1);});
test('upgrade preserves paused bytes and errors, adopts equivalent mirrors and snapshots installation options',async()=>{const old={id:'job',game:{...game,url:'https://archive.org/download/test/One.pkg',mirrors:undefined},phase:'downloading',gid:'old',dir:'/data/raff/ps4-staging/job',moved:[],paused:false,received:4096,total:8192,error:'status=500'};const c={rpc:async()=>({}),list:async()=>[],api:async()=>({}),bytes:async()=>new Uint8Array(),add:async()=>{},available:async()=>1e12};const q=new Q.Queue({catalog:{games:[game]},read:n=>n==='jobs'?JSON.stringify([old]):n==='settings'?JSON.stringify({autoInstall:true,removePackages:true}):'',write:()=>{},clientFactory:()=>c});await q.init();const j=q.jobs[0];assert.equal(j.paused,true);assert.equal(j.received,4096);assert.equal(j.error,'status=500');assert.equal(j.game.url,game.url);assert.deepEqual(j.game.mirrors,game.mirrors);assert.deepEqual(j.installOptions,{enabled:true,remove:true});});
test('catalog updates cannot switch a partial download to a different file size',async()=>{const old={id:'job',game:{...game,sizeBytes:8000,url:'https://archive.org/download/test/One.pkg',mirrors:undefined},phase:'downloading',gid:'old',dir:'/data/raff/ps4-staging/job',moved:[],paused:true,received:4096,total:8000};const c={rpc:async()=>({}),list:async()=>[],api:async()=>({}),bytes:async()=>new Uint8Array(),add:async()=>{},available:async()=>1e12};const q=new Q.Queue({catalog:{games:[game]},read:n=>n==='jobs'?JSON.stringify([old]):'',write:()=>{},clientFactory:()=>c});await q.init();assert.equal(q.jobs[0].game.url,old.game.url);assert.equal(q.jobs[0].received,4096);});
