import test from'node:test';import assert from'node:assert/strict';import policy from'../service/transport.js';import L from'../shared/core.js';
const{Policy,sameFile,retryDelay}=policy;
test('resume identity requires an unchanged strong validator or a trusted checksum',()=>{assert.equal(sameFile({etag:'"v1"',total:50},{etag:'"v1"',total:50}),true);assert.equal(sameFile({etag:'"v1"',total:50},{etag:'"v2"',total:50}),false);assert.equal(sameFile({etag:'W/"v1"',total:50},{etag:'W/"v1"',total:50}),false);assert.equal(sameFile({total:50},{total:51},'sha-256:abc'),false);assert.equal(sameFile({total:50},{total:50},'sha-256:abc'),true);});
test('Retry-After accepts seconds and HTTP dates with bounded delays',()=>{assert.equal(retryDelay('120',1000),120000);assert.equal(retryDelay(new Date(121000).toUTCString(),1000),120000);assert.equal(retryDelay('garbage'),0);assert.equal(retryDelay('9999999'),86400000);});
test('server without actual range support receives one stream and no safe-resume claim',async()=>{const q={jobs:[],settings:{connections:16},engines:new Map(),persist(){}};const p=new Policy(q);p.inspect=async()=>({status:200,range:false,total:0,etag:'"one"'});const j={game:{url:'https://example.org/a'},received:0};const result=await p.prepare(j,j.game.url);assert.equal(result.connections,1);assert.equal(j.transfer.resumeSupported,false);await assert.rejects(()=>p.resume(j),/Safe resume/);});
test('changed file keeps the existing partial file and never issues a new transfer',async()=>{const p=new Policy({persist(){}});p.inspect=async()=>({status:206,range:true,total:100,etag:'"new"'});const j={received:20,transfer:{identity:{total:100,etag:'"old"'}}};await assert.rejects(()=>p.prepare(j,'https://example.org/a'),/identity cannot/);assert.equal(j.received,20);});
test('source throttling persists its retry deadline without immediate retries',async()=>{const p=new Policy({persist(){}});p.inspect=async()=>({status:429,retryAfter:'60'});const j={received:0};await assert.rejects(()=>p.prepare(j,'https://example.org/a'),/rate limit/);assert.ok(j.retryAt>Date.now()+59000);});
test('connection budget includes other transfers on the same host',()=>{const jobs=[{id:'a',game:{url:'https://one.test/a'},transfer:{connections:3}},{id:'b',game:{url:'https://two.test/b'},transfer:{connections:4}}];const q={jobs,settings:{connections:16},engines:new Map(jobs.map(j=>[j.id,{running:true}]))};assert.equal(new Policy(q).capacity({id:'c',game:{url:'https://one.test/c'}}),1);});
test('mirrors are combined only with a trusted content checksum',async()=>{const c=new L.Client({wfm:'http://localhost',aria:'http://localhost'});let urls;c.rpc=async(m,p)=>{urls=p[0];};const base=['https://a.example/a','https://b.example/a'];await c.add(base[0],'/data/raff/ps4-staging/test','a.pkg','abc',undefined,[base[1]]);assert.deepEqual(urls,[base[0]]);await c.add(base[0],'/data/raff/ps4-staging/test','a.pkg','abc','sha-256:'+'1'.repeat(64),[base[1]]);assert.deepEqual(urls,base);});
