import test from'node:test';import assert from'node:assert/strict';import U from'../service/updates.js';import{allowedPath}from'../tools/release-bundle.mjs';
const nextVersion=(Number(U.VERSION.split('.')[0])+1)+'.0.0',nextTag='v'+nextVersion;
const repo='example/raff',digest='a'.repeat(64),asset={name:'Raff-'+nextTag+'.raffupdate',state:'uploaded',size:4096,digest:'sha256:'+digest,browser_download_url:'https://github.com/example/raff/releases/download/'+nextTag+'/Raff-'+nextTag+'.raffupdate'};
const data=()=>({tag_name:nextTag,draft:false,prerelease:false,assets:[{...asset}],body:'Notes'});
test('stable release policy orders numeric versions, ignores drafts and rejects invalid tags',()=>{assert(U.newer('1.10.0','1.9.9'));assert(!U.newer('1.1.0','1.1.0'));assert.equal(U.release({...data(),draft:true},repo),null);assert.equal(U.release({...data(),prerelease:true},repo),null);for(const v of['v1.2','1.02.0','1.2.3-beta','../../x'])assert.throws(()=>U.version(v));});
test('release assets must be digest-addressed and owned by the configured repository',()=>{assert.equal(U.release(data(),repo).sha256,digest);for(const mutation of[{digest:null},{browser_download_url:asset.browser_download_url.replace('example/','attacker/')},{browser_download_url:asset.browser_download_url+'?token=secret'},{size:3*1024**3}])assert.throws(()=>U.release({...data(),assets:[{...asset,...mutation}]},repo));for(const r of['','/raff','foo/../bar','x/y?z','http://github.com/a/b'])assert.throws(()=>U.repository(r));});
test('bundle paths cannot replace data, traverse folders or contain session tokens',()=>{for(const p of['../settings.json','assets/../secret','assets/.token','/data/a','runtime\\file','jobs.json','.session-token','assets//a','assets/a\0b'])assert(!allowedPath(p),p);for(const p of['eboot.bin','assets/update-config.json','runtime/ca-bundle.crt'])assert(allowedPath(p));});
function fixture(config={repository:repo}){let now=100000,seq=0;const saved={},calls=[];let status={status:'complete',totalLength:'100',completedLength:'100'},native={phase:'ready'};let busy=false;const u=new U.Updates({config,client:{ensureDir:async()=>{},rpc:async(m,args)=>{calls.push([m,args]);if(m==='tellStatus')return status;return args?.[1]?.gid||'ok';}},fs:(op)=>op==='space'?1e12:JSON.stringify(data()),native:(op)=>{calls.push([op]);return native;},read:n=>saved[n],write:(n,v)=>saved[n]=v,id:()=>String(++seq).padStart(16,'0'),clock:()=>now,busy:()=>busy});return{u,saved,calls,time:v=>now=v,status:v=>status=v,native:v=>native=v,busy:v=>busy=v};}
test('no configured repository means no automatic network call',async()=>{const f=fixture({repository:''});await f.u.tick();assert.equal(f.calls.length,0);assert.equal(f.u.status().phase,'unconfigured');});
test('check, notification, explicit download, verification and apply form a gated lifecycle',async()=>{const f=fixture();await f.u.check();assert.equal(f.u.state.phase,'checking');await f.u.tick();assert.equal(f.u.state.phase,'available');const check=f.calls.find(c=>c[0]==='addUri')[1][1];assert.equal(check['check-certificate'],'true');await f.u.download();assert.equal(f.u.state.phase,'downloading');assert.equal(f.calls.filter(c=>c[0]==='addUri')[1][1][1].checksum,'sha-256='+digest);await assert.rejects(()=>f.u.apply(),/verified/);f.status({status:'complete',totalLength:'4096',completedLength:'4096'});await f.u.tick();assert.equal(f.u.state.phase,'verifying');await f.u.tick();assert.equal(f.u.state.phase,'ready');f.busy(true);await assert.rejects(()=>f.u.apply(),/Pause/);f.busy(false);await f.u.apply();assert.equal(f.u.state.phase,'applying');});
test('size overrun and native verification errors cannot install an update',async()=>{const f=fixture();await f.u.check();f.status({status:'active',totalLength:'2000000',completedLength:'2'});await f.u.tick();assert.equal(f.u.state.phase,'error');assert(f.calls.some(c=>c[0]==='forceRemove'));const g=fixture();g.u.state={phase:'verifying'};g.native({phase:'error',error:'Checksum mismatch'});await g.u.tick();assert.equal(g.u.state.phase,'error');await assert.rejects(()=>g.u.apply());});
test('same repository reattaches a download after service restart without enqueueing twice',()=>{const f=fixture();f.u.state={phase:'downloading',gid:'0000000000000001',release:U.release(data(),repo)};f.u.save();const restored=new U.Updates({config:{repository:repo},read:n=>f.saved[n],write:()=>{}});assert.equal(restored.state.gid,'0000000000000001');const changed=new U.Updates({config:{repository:'another/project'},read:n=>f.saved[n],write:()=>{}});assert.equal(changed.state.phase,'idle');});
test('background checks back off and manual requests cannot flood GitHub',async()=>{const f=fixture();await f.u.check(true);await f.u.tick();f.u.state.phase='current';await f.u.check(true);assert.equal(f.calls.filter(c=>c[0]==='addUri').length,1);await f.u.check();assert.equal(f.calls.filter(c=>c[0]==='addUri').length,1);});
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
test('update handoff stops a late resident service after preparation has started',()=>{
 const source=readFileSync(new URL('../service/main.js',import.meta.url),'utf8');
 const code=source.slice(source.indexOf('function updateTick()'),source.indexOf('setTimeout(updateTick,15000);'));
 for(const phase of ['waiting-close','preserving-art','error']){
  let stopped=0,persisted=0,failed=0;
  const ctx={updater:{tick:()=>Promise.resolve(),state:{phase:'applying'},fail:()=>failed++},queue:{persist:()=>persisted++},nativeStop:()=>stopped++,nativeRead:()=>JSON.stringify({phase,error:'retry'}),setTimeout(){},console};
  runInNewContext(code+';updateTick();',ctx);
  assert.equal(stopped,phase==='error'?0:1,phase);assert.equal(persisted,stopped);assert.equal(failed,phase==='error'?1:0);
 }
});
