(function(root){'use strict';
const MAX=524288,encoder=s=>{const t=unescape(encodeURIComponent(s));return Uint8Array.from(t,c=>c.charCodeAt(0));},decode=b=>{const s=new TextDecoder().decode(b);if(s.includes('\ufffd'))throw Error('Torrent filename is not valid UTF-8');return s;};
function digest(b,algorithm='sha1'){if(root.nativeDigest)return root.nativeDigest(algorithm,b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));return require('node:crypto').createHash(algorithm).update(b).digest('hex');}
function base64(b){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',out=[];for(let i=0;i<b.length;i+=3){const v=(b[i]<<16)|((b[i+1]||0)<<8)|(b[i+2]||0);out.push(chars[v>>>18&63]+chars[v>>>12&63]+(i+1<b.length?chars[v>>>6&63]:'=')+(i+2<b.length?chars[v&63]:'='));}return out.join('');}
function unbase64(s){if(typeof s!=='string'||s.length>MAX*4/3+8||s.length%4||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(s))throw Error('Invalid torrent base64');const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',out=[];for(let i=0;i<s.length;i+=4){const v=(chars.indexOf(s[i])<<18)|(chars.indexOf(s[i+1])<<12)|(Math.max(0,chars.indexOf(s[i+2]))<<6)|Math.max(0,chars.indexOf(s[i+3]));out.push(v>>>16&255);if(s[i+2]!=='=')out.push(v>>>8&255);if(s[i+3]!=='=')out.push(v&255);}return Uint8Array.from(out);}
function segment(s){if(typeof s!=='string'||!s||s.length>220||/^[. ]|[. ]$|[\x00-\x1f\x7f/\\:*?"<>|]/.test(s)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(s))throw Error('Unsafe torrent filename');return s;}
function url(s,tracker=false){if(typeof s!=='string'||s.length>2048||!new RegExp(tracker?'^(https?|udp)://':'^https://').test(s)||/[\x00-\x20\\]/.test(s)||!/^([a-z]+):\/\/[A-Za-z0-9.-]+(?::[0-9]{1,5})?(?:[/?#]|$)/.test(s)||s.split('/')[2].includes('@'))throw Error('Invalid source URL');return s;}
function parse(bytes){if(!(bytes instanceof Uint8Array)||bytes.length<16||bytes.length>MAX)throw Error('Torrent metadata limit is 512 KiB');let at=0,nodes=0,infoStart=-1,infoEnd=-1;
 const text=(s,e)=>{if(e-s>20)throw Error('Invalid torrent number');return String.fromCharCode.apply(null,Array.from(bytes.slice(s,e)));};
 function value(depth){if(depth>24||++nodes>24000)throw Error('Torrent metadata is too complex');const c=bytes[at++];if(c===105){const start=at;while(at<bytes.length&&bytes[at]!==101)at++;const s=text(start,at++);if(!/^(0|-[1-9]\d*|[1-9]\d*)$/.test(s)||!Number.isSafeInteger(+s))throw Error('Invalid torrent integer');return+s;}if(c===108||c===100){const result=c===108?[]:Object.create(null);let previous='';while(bytes[at]!==101){if(at>=bytes.length)throw Error('Truncated torrent');if(c===108)result.push(value(depth+1));else{const keyBytes=value(depth+1);if(!(keyBytes instanceof Uint8Array)||keyBytes.length>256)throw Error('Invalid torrent dictionary');const key=decode(keyBytes);if(Object.hasOwn(result,key)||previous&&key<=previous)throw Error('Unsorted or duplicate torrent key');previous=key;const start=at;result[key]=value(depth+1);if(depth===0&&key==='info'){infoStart=start;infoEnd=at;}}}at++;return result;}if(c>=48&&c<=57){const start=--at;while(at<bytes.length&&bytes[at]!==58)at++;const s=text(start,at++);if(!/^(0|[1-9]\d*)$/.test(s)||+s>MAX||at+(+s)>bytes.length)throw Error('Invalid torrent string');const b=bytes.slice(at,at+(+s));at+=+s;return b;}throw Error('Invalid bencode');}
 const meta=value(0),i=meta?.info;if(at!==bytes.length||infoStart<0||!i||Array.isArray(i)||i['meta version'])throw Error('Only BitTorrent v1 metadata is supported; v2 and hybrid torrents are not supported');
 const name=segment(decode(i['name.utf-8']||i.name)),pieceLength=i['piece length'];if(!Number.isSafeInteger(pieceLength)||pieceLength<16384||pieceLength>16777216||pieceLength&(pieceLength-1))throw Error('Invalid torrent piece length');
 if(!(i.pieces instanceof Uint8Array)||i.pieces.length%20||!i.pieces.length)throw Error('Invalid torrent piece hashes');
 let files=[],total=0;function file(f,path){if(!Number.isSafeInteger(f.length)||f.length<0||f.length>16*1024**4)throw Error('Invalid torrent size');if(f['symlink path']||f.attr&&decode(f.attr).includes('l'))throw Error('Torrent symlinks are forbidden');if(path.length>16||path.join('/').length>1024)throw Error('Torrent path is too long');total+=f.length;if(!Number.isSafeInteger(total)||total>16*1024**4)throw Error('Torrent exceeds storage limit');files.push({index:files.length+1,path:path.join('/'),length:f.length,padding:!!(f.attr&&decode(f.attr).includes('p'))});}
 if(i.files){if(i.length!==undefined||!Array.isArray(i.files)||!i.files.length||i.files.length>2048)throw Error('Torrent file limit is 2048');for(const f of i.files){const path=f['path.utf-8']||f.path;if(!Array.isArray(path)||!path.length)throw Error('Invalid torrent file path');file(f,[name,...path.map(x=>segment(decode(x)))]);}}else file(i,[name]);
 const paths=new Set();for(const f of files){const k=f.path.toLowerCase();if(paths.has(k)||[...paths].some(p=>k.startsWith(p+'/')||p.startsWith(k+'/')))throw Error('Conflicting torrent paths');paths.add(k);}
 if(!total||i.pieces.length/20!==Math.ceil(total/pieceLength))throw Error('Torrent piece count does not match file sizes');
 const trackers=[];for(const t of[meta.announce,...(Array.isArray(meta['announce-list'])?meta['announce-list'].flat():[])].filter(Boolean)){const v=url(decode(t),true);if(!trackers.includes(v))trackers.push(v);if(trackers.length>32)throw Error('Too many trackers');}
 const seeds=meta['url-list']?[].concat(meta['url-list']).map(x=>url(decode(x))):[];if(seeds.length>8)throw Error('Too many web seeds');
 return{name,infoHash:digest(bytes.slice(infoStart,infoEnd)),files,total,pieceLength,trackers,webSeeds:seeds,private:i.private===1};
}
function magnet(value){if(typeof value!=='string'||value.length>4096||!value.startsWith('magnet:?')||/[\x00-\x20]/.test(value))throw Error('Invalid magnet link');const pairs=value.slice(8).split('&').map(p=>{const n=p.indexOf('=');return[decodeURIComponent(n<0?p:p.slice(0,n)),decodeURIComponent(n<0?'':p.slice(n+1))];});const xt=pairs.filter(p=>p[0]==='xt');if(xt.length!==1||!/^urn:btih:(?:[0-9a-fA-F]{40}|[A-Z2-7a-z]{32})$/.test(xt[0][1]))throw Error('Use a BitTorrent v1 magnet with a hexadecimal or base32 info hash');let infoHash=xt[0][1].slice(9).toLowerCase();if(infoHash.length===32){let bits=0,buffer=0,out='';for(const c of infoHash.toUpperCase()){buffer=(buffer<<5)|'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);bits+=5;if(bits>=8){bits-=8;out+=((buffer>>>bits)&255).toString(16).padStart(2,'0');}}infoHash=out;}const allowed=[['xt','urn:btih:'+infoHash]];for(const[k,v]of pairs){if(k==='tr'){url(v,true);allowed.push([k,v]);}else if(k==='dn')allowed.push([k,segment(v)]);else if(k==='x.pe'){if(!/^(?:\d{1,3}\.){3}\d{1,3}:\d{1,5}$/.test(v)||v.split(':')[0].split('.').some(n=>+n>255)||+v.split(':')[1]<1||+v.split(':')[1]>65535)throw Error('Invalid explicit peer');allowed.push([k,v]);}else if(k!=='xt')throw Error('Unsupported magnet parameter: '+k);}if(allowed.length>36)throw Error('Magnet has too many trackers');return{infoHash,uri:'magnet:?'+allowed.map(([k,v])=>k+'='+encodeURIComponent(v)).join('&')};}
// aria2's stopped-result file counters can be zero even when the piece bitfield is retained.
// Count only verified piece intersections with selected files, including shared boundary pieces.
function completed(files,selected,pieceLength,bitfield){if(typeof bitfield!=='string'||!/^[a-f0-9]*$/i.test(bitfield))return null;let offset=0,total=0;for(const f of files){if(Number.isSafeInteger(f.offset))offset=f.offset;const end=offset+f.length;if(selected.includes(f.index))for(let p=Math.floor(offset/pieceLength);p<Math.ceil(end/pieceLength);p++){const byte=parseInt(bitfield.slice(Math.floor(p/8)*2,Math.floor(p/8)*2+2),16);if(Number.isFinite(byte)&&(byte&(128>>(p%8))))total+=Math.max(0,Math.min(end,(p+1)*pieceLength)-Math.max(offset,p*pieceLength));}offset=end;}return total;}
const api={MAX,parse,magnet,base64,unbase64,digest,segment,url,encoder,completed};if(typeof module!=='undefined')module.exports=api;else root.RaffBT=api;
})(globalThis);
