(function(root){
'use strict';
const parse=(s,f=null)=>{try{return JSON.parse(s);}catch{return f;}};
const stamp=()=>new Date().toISOString();
const dependencies=root.RaffDependencies||(typeof require==='function'?require('./dependencies.js'):null);
function identifier(){const b=new Uint8Array(16);root.crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function path(value){if(typeof value!=='string'||value.length>2048||!/^\/(data|mnt)(\/|$)/.test(value)||/[\x00-\x1f\\]/.test(value)||value.split('/').some(x=>x==='..'||x==='.'))throw Error('Invalid target path');return value.replace(/\/{2,}/g,'/').replace(/\/$/,'');}
const dirname=p=>p.slice(0,p.lastIndexOf('/'));
const basename=p=>p.slice(p.lastIndexOf('/')+1);
const ext=p=>(p.split('.').pop()||'').toLowerCase();
function relativeFile(parent,name){if(!name||name.startsWith('/')||/^[A-Za-z]:/.test(name)||/[\x00-\x1f]/.test(name))throw Error('Unsafe referenced file');const parts=name.replace(/\\/g,'/').split('/');if(parts.some(x=>x==='..'))throw Error('Referenced file escapes game folder');return path(parent+'/'+parts.filter(x=>x&&x!=='.').join('/'));}
function cue(text,filename,stat){
 const files=[],tracks=[];let current=null;
 for(const line of text.split(/\r?\n/)){
  const f=line.match(/^\s*FILE\s+(?:"([^"]+)"|(\S+))\s+(BINARY|WAVE|MP3|AIFF|MOTOROLA)\s*$/i);
  if(f){const target=relativeFile(dirname(filename),f[1]||f[2]),info=stat(target);if(!info||info.type!=='file'||info.size<=0)throw Error('Missing CUE track: '+basename(target));current=target;files.push(target);}
  else if(/^\s*FILE\b/i.test(line))throw Error('Invalid CUE FILE declaration');
  const t=line.match(/^\s*TRACK\s+(\d+)\s+(\S+)/i);if(t){if(!current)throw Error('TRACK precedes FILE');const number=Number(t[1]);if(tracks.some(x=>x.number===number))throw Error('Duplicate CUE track');tracks.push({number,type:t[2],file:current});}
 }
 if(!files.length||!tracks.length)throw Error('CUE has no complete tracks');return{kind:'cue',files:[...new Set(files)],tracks,valid:true};
}
function playlist(text,filename,stat){const files=[];for(const raw of text.split(/\r?\n/)){const name=raw.trim();if(!name||name.startsWith('#'))continue;const target=relativeFile(dirname(filename),name);if(!['cue','chd','pbp','ccd','iso'].includes(ext(target)))throw Error('Unsupported disc in M3U');const s=stat(target);if(!s||s.type!=='file'||!s.size)throw Error('Missing M3U disc: '+name);if(!files.includes(target))files.push(target);}if(!files.length)throw Error('Empty M3U');return{kind:'m3u',files,valid:true};}
function info(text){const out={};for(const line of text.split(/\r?\n/)){const m=line.match(/^\s*(\w+)\s*=\s*(.*?)\s*$/);if(m)out[m[1]]=m[2].startsWith('"')?parse(m[2],m[2].slice(1,-1)):m[2];}return out;}
function fts(value){return String(value||'').normalize('NFKC').replace(/[\x00-\x1f]/g,' ').split(/[^\p{L}\p{N}]+/u).filter(Boolean).slice(0,12).map(t=>'"'+t.replace(/"/g,'""')+'"*').join(' AND ');}
class Library{
 constructor({sql,fs,registry,settings,saveSettings,clock=()=>Date.now()}){this.sql=sql;this.fs=fs;this.registry=registry;this.settings=settings;this.saveSettings=saveSettings;this.clock=clock;this.scans=new Map();this.coreMap=new Map(registry.cores.map(c=>[c.id,c]));}
 rows(q,p=[]){return this.sql(q,p).rows;}
 run(q,p=[]){return this.sql(q,p);}
 init(){
  const config={executable:'/data/homebrew/PPSA99169/eboot.bin',coreDirectory:'/data/homebrew/PPSA99169/cores',contentDirectory:'/data/homebrew/PPSA99169/content',firmwareDirectory:'/data/homebrew/PPSA99169/system',saveDirectory:'/data/homebrew/PPSA99169/savefiles',playlistDirectory:'/data/homebrew/PPSA99169/playlists',launchMode:'export',runtime:'PS5',firmware:'13.60',installedCores:[]};
  this.run('INSERT OR IGNORE INTO target_profiles VALUES(?,?,?,?,?)',['ps5-local','PlayStation 5','ps5',JSON.stringify(config),null]);
  if(!this.rows('SELECT value FROM setup WHERE key=?',['favorites-migrated']).length){for(const key of this.settings.favorites||[]){const g=this.rows('SELECT id FROM catalog.games WHERE legacy_key=?',[key])[0];if(g)this.run('INSERT OR IGNORE INTO favorites VALUES(?,?)',[g.id,stamp()]);}this.run('INSERT INTO setup VALUES(?,?)',['favorites-migrated','true']);}
  // Interrupted scans remain visible and can be resumed; no game files are removed.
  for(const row of this.rows("SELECT * FROM scan_jobs WHERE state IN ('running','paused') LIMIT 64")){const progress=parse(row.progress,{});progress.paused=true;this.scans.set(row.id,{...progress,id:row.id,targetId:row.target_id,state:'paused'});}
  this.detectTarget('ps5-local');
 }
 profiles(){return this.rows('SELECT * FROM target_profiles ORDER BY name').map(r=>({...r,configuration:parse(r.configuration,{})}));}
 profile(id='ps5-local'){const row=this.rows('SELECT * FROM target_profiles WHERE id=?',[id])[0];if(!row)throw Error('Unknown target device');return{...row,configuration:parse(row.configuration,{})};}
 configureTarget(value){const previous=this.profile(value.id||'ps5-local');const c={...previous.configuration};for(const k of ['executable','coreDirectory','contentDirectory','firmwareDirectory','saveDirectory','playlistDirectory'])if(value[k]!==undefined)c[k]=path(value[k]);if(value.launchMode&&value.launchMode!=='export')throw Error('This target requires an audited launch bridge; export is available');this.run('UPDATE target_profiles SET configuration=?,detected_at=NULL WHERE id=?',[JSON.stringify(c),previous.id]);return this.detectTarget(previous.id);}
 detectTarget(id){const p=this.profile(id),c=p.configuration,installed=[];let offset=0;try{do{const page=this.fs('list',c.coreDirectory,offset);for(const file of page.entries){if(file.type!=='file'||!/_libretro\.(so|dll|dylib|self|elf)$/i.test(file.name))continue;const cid=file.name.replace(/\.[^.]+$/,'');if(!this.coreMap.has(cid))continue;let local={};try{local=info(this.fs('read',dirname(file.path)+'/'+cid+'.info'));}catch{}installed.push({id:cid,path:file.path,size:file.size,mtime:file.mtime,version:local.display_version||null,versionEvidence:local.display_version?'installed-info':'unknown',info:local});}offset=page.next;}while(offset!==null);}catch(e){c.detectionError=e.message;}
  c.installedCores=installed;c.executablePresent=this.fs('stat',c.executable)?.type==='file';this.run('UPDATE target_profiles SET configuration=?,detected_at=? WHERE id=?',[JSON.stringify(c),stamp(),id]);return this.profile(id);
 }
 platforms(target='ps5-local'){
  const p=this.profile(target),installed=new Set(p.configuration.installedCores.map(c=>c.id));
  const local=new Map(this.rows('SELECT platform,count(*) AS n FROM installations WHERE target_id=? GROUP BY platform',[target]).map(r=>[r.platform,r.n]));
  return this.rows("SELECT * FROM catalog.platforms ORDER BY CASE WHEN kind='standalone' THEN 0 ELSE 1 END,family,name LIMIT 512").map(r=>{const cores=parse(r.cores,[]);return{...r,cores,availableCores:cores.filter(c=>installed.has(c)),localCount:local.get(r.id)||0,verifiedPlayable:0,downloadableReleases:this.settings.authorizedLegacy&&r.kind==='standalone'?r.release_count:0,availability:r.kind==='standalone'?'standalone':cores.some(c=>installed.has(c))?'core-installed':'core-unavailable'};});
 }
 browse(v={}){
  const started=this.clock();const size=Math.min(60,Math.max(8,Number(v.limit)||24)),offset=Math.max(0,Math.min(1000000,Number(v.offset)||0));const where=[],args=[];const search=fts(v.query);
  let from='catalog.games g';if(search){from+=' JOIN catalog.search s ON s.rowid=g.rowid';where.push('search MATCH ?');args.push(search);}
  if(v.platform){where.push('g.platform=?');args.push(String(v.platform));}
  if(v.scope==='favorites')where.push('EXISTS(SELECT 1 FROM favorites f WHERE f.game_id=g.id)');
  if(v.scope==='library'){where.push('EXISTS(SELECT 1 FROM installations i WHERE i.game_id=g.id AND i.target_id=?)');args.push(v.target||'ps5-local');}
  if(v.genre){where.push("json_extract(g.metadata,'$.genre')=?");args.push(String(v.genre));}
  const clause=where.length?' WHERE '+where.join(' AND '):'';
  const order=v.sort==='rating'?"coalesce(json_extract(g.metadata,'$.legacy.score'),-1) DESC,g.search_title,g.id":v.sort==='popular'?"coalesce(json_extract(g.metadata,'$.legacy.popularityScore'),json_extract(g.metadata,'$.legacy.downloads'),-1) DESC,g.search_title,g.id":v.sort==='recent'?'g.added_at DESC,g.search_title,g.id':v.sort==='year'?"coalesce(json_extract(g.metadata,'$.year'),0) DESC,g.search_title,g.id":'g.search_title,g.id';
  const total=this.rows('SELECT count(*) AS n FROM '+from+clause,args)[0].n;
  const rows=this.rows('SELECT g.id,g.platform,g.title,g.cover,g.legacy_key,g.metadata,EXISTS(SELECT 1 FROM favorites f WHERE f.game_id=g.id) AS favorite FROM '+from+clause+' ORDER BY '+order+' LIMIT ? OFFSET ?',[...args,size,offset]);
  return{elapsedMs:this.clock()-started,total,offset,limit:size,query:v.query||'',platform:v.platform||'',scope:v.scope||'discover',items:rows.map(r=>{const m=parse(r.metadata,{});return{id:r.id,title:r.title,platform:r.platform,cover:r.cover,favorite:!!r.favorite,year:m.year||null,genre:m.genre||m.legacy?.genre||null,legacyKey:r.legacy_key,compatibility:'untested'};})};
 }
 detail(id,offset=0){
  const g=this.rows('SELECT * FROM catalog.games WHERE id=?',[id])[0];if(!g)throw Error('Unknown game');
  const metadata=parse(g.metadata,{}),p=this.profile();const platform=this.rows('SELECT * FROM catalog.platforms WHERE id=?',[g.platform])[0];const releases=this.rows('SELECT * FROM catalog.releases WHERE game_id=? ORDER BY source_key LIMIT 60 OFFSET ?',[id,Math.max(0,Number(offset)||0)]).map(r=>({...r,region:parse(r.region,[]),revision:parse(r.revision,[]),languages:parse(r.languages,{}),metadata:parse(r.metadata,{}),assets:this.rows('SELECT * FROM catalog.assets WHERE release_id=?',[r.id])}));
  const legacy=metadata.legacy||{};metadata.critic=releases.map(r=>r.metadata.critic).find(Boolean)||null;metadata.userRating=legacy.rating?{score:legacy.rating,scale:5,count:legacy.ratingCount||null,source:'PlayStation Store',url:legacy.ratingSource,date:legacy.ratingCheckedAt}:null;metadata.releaseDate=releases.map(r=>r.metadata.releaseDate).find(Boolean)||legacy.date||null;const cache=parse(this.rows('SELECT value FROM metadata_cache WHERE game_id=?',[id])[0]?.value,{});
  return{...g,metadata:{...metadata,...cache},releases,releaseTotal:this.rows('SELECT count(*) n FROM catalog.releases WHERE game_id=?',[id])[0].n,releaseOffset:offset,platform,compatibility:{coreAvailability:parse(platform.cores,[]).filter(c=>p.configuration.installedCores.some(i=>i.id===c)),gameEvidence:[],status:platform.kind==='standalone'?'untested':parse(platform.cores,[]).some(c=>p.configuration.installedCores.some(i=>i.id===c))?'untested':'unsupported',setup:'not-checked',localLaunch:'not-tested'},installations:this.rows('SELECT * FROM installations WHERE game_id=? AND target_id=?',[id,p.id]).map(r=>({...r,metadata:parse(r.metadata,{})})),favorite:!!this.rows('SELECT 1 FROM favorites WHERE game_id=?',[id]).length,downloadAuthorization:'repository-confirmation-required'};
 }
 favorite(id,enabled){const g=this.rows('SELECT legacy_key FROM catalog.games WHERE id=?',[id])[0];if(!g)throw Error('Unknown game');if(enabled)this.run('INSERT OR IGNORE INTO favorites VALUES(?,?)',[id,stamp()]);else this.run('DELETE FROM favorites WHERE game_id=?',[id]);if(g.legacy_key){const set=new Set(this.settings.favorites||[]);enabled?set.add(g.legacy_key):set.delete(g.legacy_key);this.settings.favorites=[...set];this.saveSettings();}return{ok:true};}
 view(value){if(value.value!==undefined){if(JSON.stringify(value.value).length>8192)throw Error('Browsing state too large');this.run('INSERT OR REPLACE INTO view_state VALUES(?,?)',[value.id||'main',JSON.stringify(value.value)]);}return parse(this.rows('SELECT value FROM view_state WHERE id=?',[value.id||'main'])[0]?.value,{});}
 validate(file,platform){const s=this.fs('stat',file);if(!s||s.type!=='file'||s.size<=0)throw Error('File does not exist or is empty');let result={valid:true,files:[file],size:s.size,mtime:s.mtime,checks:['file-present'],compatibility:'untested'};
  if(ext(file)==='cue')result={...result,...cue(this.fs('read',file),file,p=>this.fs('stat',p))};
  else if(ext(file)==='m3u'){result={...result,...playlist(this.fs('read',file),file,p=>this.fs('stat',p))};for(const item of result.files)if(ext(item)==='cue')cue(this.fs('read',item),item,p=>this.fs('stat',p));}
  else if(platform==='sony-playstation'&&ext(file)==='bin')throw Error('Import the CUE file; a loose PS1 BIN does not describe all tracks');
  const p=this.rows('SELECT kind,name FROM catalog.platforms WHERE id=?',[platform])[0];if(!p)throw Error('Select a platform');const extensions=new Set((this.registry.platforms[platform]?.cores||[]).flatMap(id=>this.coreMap.get(id)?.extensions||[]));for(const e of platform==='ps2'?['iso','chd','cso','zso']:platform==='switch'?['nsp','xci']:['ps4','ps5'].includes(platform)?['pkg','fpkg','ffpfsc']:[])extensions.add(e);if(!extensions.has(ext(file)))throw Error('This format is not declared for the selected platform');
  if(p.kind==='arcade'||/MAME|FinalBurn|Arcade/i.test(p.name)){result.setup='romset-unverified';result.requirements=['Exact core version and ROM-set DAT','Parent and BIOS archives','Required CHD disks'];}
  if(p.kind==='engine'){result.setup='engine-data-unverified';result.requirements=['Validate the engine-specific game data manifest'];}
  return result;
 }
 importFile(v){if(String(v.path).endsWith(".raff.json"))return this.importManifest(v);const file=path(v.path),target=this.profile(v.target),validation=this.validate(file,v.platform);let game=null;
  if(v.gameId){game=this.rows('SELECT id,platform FROM catalog.games WHERE id=?',[v.gameId])[0];if(!game||game.platform!==v.platform)throw Error('Game and platform differ');}
  if(!game){const matches=this.rows('SELECT DISTINCT g.id,g.platform FROM catalog.assets a JOIN catalog.releases r ON r.id=a.release_id JOIN catalog.games g ON g.id=r.game_id WHERE a.filename=? AND a.size=? AND g.platform=? LIMIT 2',[basename(file),validation.size,v.platform]);if(matches.length===1)game=matches[0];}
  const existing=this.rows('SELECT id FROM installations WHERE target_id=? AND path=?',[target.id,file])[0];const id=existing?.id||identifier();const data={title:basename(file).replace(/\.[^.]+$/,''),validation,matchEvidence:v.gameId?'user-selected':game?'exact-filename-size':'unmatched',coreOverride:v.core||null};
  this.run('INSERT INTO installations VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(target_id,path) DO UPDATE SET game_id=excluded.game_id,metadata=excluded.metadata,last_seen=excluded.last_seen',[id,game?.id||null,null,target.id,file,v.platform,v.core||null,JSON.stringify(data),stamp(),stamp()]);return{ok:true,id,duplicate:!!existing,matched:!!game,validation};
 }
 importManifest(v){const filename=path(v.path),manifest=JSON.parse(this.fs('read',filename)),target=this.profile(v.target),core=target.configuration.installedCores.find(c=>c.id===manifest.core);const result=dependencies.validate({manifest,folder:dirname(filename),core,fs:this.fs,resolve:relativeFile});const file=relativeFile(dirname(filename),manifest.content);const imported=this.importFile({...v,path:file,core:manifest.core});const row=this.rows('SELECT metadata FROM installations WHERE id=?',[imported.id])[0];const metadata=parse(row.metadata,{});metadata.dependencies=result;this.run('UPDATE installations SET metadata=? WHERE id=?',[JSON.stringify(metadata),imported.id]);return{...imported,dependencies:result};}
 local(v={}){const total=this.rows('SELECT count(*) n FROM installations WHERE target_id=?',[v.target||'ps5-local'])[0].n;return{total,items:this.rows('SELECT * FROM installations WHERE target_id=? ORDER BY added_at DESC LIMIT 60 OFFSET ?',[v.target||'ps5-local',Math.max(0,Number(v.offset)||0)]).map(r=>({...r,metadata:parse(r.metadata,{})}))};}
 scan(v){const target=this.profile(v.target),folder=path(v.path||target.configuration.contentDirectory);if(this.fs('stat',folder)?.type!=='directory')throw Error('Scan folder does not exist');if(!this.rows('SELECT id FROM catalog.platforms WHERE id=?',[v.platform]).length)throw Error('Select a scan platform');const id=identifier(),job={id,targetId:target.id,platform:v.platform,pending:[{path:folder,offset:0,depth:0}],visited:0,imported:0,duplicates:0,failed:0,errors:[],state:'running',paused:false};this.scans.set(id,job);this.persistScan(job);return{id};}
 persistScan(j){this.run('INSERT INTO scan_jobs VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,progress=excluded.progress',[j.id,j.targetId,j.state,JSON.stringify(j),stamp()]);}
 scanAction(id,action){const j=this.scans.get(id);if(!j)throw Error('Unknown scan');if(action==='cancel'){j.state='canceled';j.pending=[];}else if(action==='resume'){j.state='running';j.paused=false;}else if(action==='pause'){j.state='paused';j.paused=true;}else throw Error('Unknown scan action');this.persistScan(j);return{ok:true};}
 tick(){for(const j of this.scans.values()){
  if(j.state!=='running'||j.paused)continue;const next=j.pending.shift();if(!next){j.state='done';this.persistScan(j);continue;}
  try{const page=this.fs('list',next.path,next.offset);const p=this.registry.platforms[j.platform],extensions=new Set((p?.cores||[]).flatMap(c=>this.coreMap.get(c)?.extensions||[]));for(const extra of j.platform==='ps2'?['iso','chd','cso','zso']:j.platform==='switch'?['nsp','xci']:['ps4','ps5'].includes(j.platform)?['pkg','fpkg','ffpfsc']:[])extensions.add(extra);
   for(const entry of page.entries){j.visited++;if(entry.type==='directory'&&next.depth<8&&j.pending.length<10000)j.pending.push({path:entry.path,offset:0,depth:next.depth+1});if(entry.type==='directory'&&(next.depth>=8||j.pending.length>=10000)){j.failed++;if(j.errors.length<30)j.errors.push({path:entry.path,error:'Scan depth or queue limit reached; scan this folder separately'});}if(entry.type!=='file'||!extensions.has(ext(entry.name)))continue;if(j.platform==='sony-playstation'&&ext(entry.name)==='bin')continue;try{const r=this.importFile({target:j.targetId,path:entry.path,platform:j.platform});r.duplicate?j.duplicates++:j.imported++;}catch(e){j.failed++;if(j.errors.length<30)j.errors.push({path:entry.path,error:e.message});}}
   if(page.next!==null)j.pending.unshift({...next,offset:page.next});
  }catch(e){j.failed++;if(j.errors.length<30)j.errors.push({path:next.path,error:e.message});}
  this.persistScan(j);break;
 }}
 scanStatus(){return Array.from(this.scans.values()).map(({pending,...j})=>({...j,remainingFolders:pending.length}));}
 firmware(coreId,targetId,region){const target=this.profile(targetId),core=this.coreMap.get(coreId);if(!core)throw Error('Unknown core');const installed=target.configuration.installedCores.find(c=>c.id===coreId);if(!installed)return{coreAvailable:false,status:'unsupported',files:[]};
  const local=installed.info||{},requirements=[];for(let n=0;n<Number(local.firmware_count||0);n++){const f='firmware'+n+'_';requirements.push({path:local[f+'path'],optional:local[f+'opt']==='true',description:local[f+'desc'],md5:(String(local.notes||'').split('|').find(note=>note.includes(local[f+'path']+' (md5)'))||'').match(/[a-f0-9]{32}/i)?.[0]||null});}
  const defs=requirements.length?requirements:core.firmware;const files=defs.map(f=>{let state;try{state=this.fs('stat',relativeFile(target.configuration.firmwareDirectory,f.path));}catch{}let actual=null;if(state?.type==='file'&&state.size>0&&f.md5)try{actual=this.fs('md5',relativeFile(target.configuration.firmwareDirectory,f.path));}catch{}return{...f,present:state?.type==='file'&&state.size>0,hashStatus:actual?(actual.toLowerCase()===f.md5.toLowerCase()?'verified':'mismatch'):'not-verified',evidence:requirements.length?'installed-core-info':'registry-info',version:installed.version};});
  const regional=/^mednafen_psx(?:_hw)?_libretro$/.test(coreId);const wanted=/Japan|Asia|JP/i.test(region||'')?'scph5500.bin':/USA|US|America/i.test(region||'')?'scph5501.bin':/Europe|EU|Australia/i.test(region||'')?'scph5502.bin':null;for(const f of files)f.requiredForSelectedRegion=regional?(wanted?f.path===wanted:null):!f.optional;return{coreAvailable:true,coreVersion:installed.version,versionEvidence:installed.versionEvidence,files,region:region||null,status:regional&&!wanted?'select-release-region':files.some(f=>f.requiredForSelectedRegion&&(!f.present||f.hashStatus==='mismatch'))?'missing-or-invalid-firmware':'requirements-present-gameplay-unverified'};
 }
 exportPlaylist(v){const target=this.profile(v.target),rows=v.installationId?this.rows('SELECT * FROM installations WHERE id=? AND target_id=?',[v.installationId,target.id]):this.rows('SELECT * FROM installations WHERE target_id=? ORDER BY path LIMIT 512 OFFSET ?',[target.id,Math.max(0,Number(v.offset)||0)]);if(!rows.length)throw Error('No imported files to export');const seen=new Set(),items=[];
  for(const r of rows){if(seen.has(r.path))continue;seen.add(r.path);const m=parse(r.metadata,{});const selected=v.core||r.core_id||m.coreOverride;const core=target.configuration.installedCores.find(c=>c.id===selected);if(selected&&!core)throw Error('Selected core is not installed on this target');if(selected)this.run('UPDATE installations SET core_id=? WHERE id=?',[selected,r.id]);items.push({path:r.path,label:m.title||basename(r.path),core_path:core?.path||'DETECT',core_name:core?this.coreMap.get(core.id)?.name||core.id:'DETECT',crc32:'DETECT',db_name:''});}
  const playlist={version:'1.5',default_core_path:'',default_core_name:'',label_display_mode:0,right_thumbnail_mode:0,left_thumbnail_mode:0,sort_mode:0,items};const name='Raff-'+identifier()+'.lpl',file=(this.fs('stat',target.configuration.playlistDirectory)?.type==='directory'?target.configuration.playlistDirectory:'/data/raff/native-v5/exports')+'/'+name;this.fs('export',file,JSON.stringify(playlist,null,2));return{ok:true,path:file,count:items.length,offset:Math.max(0,Number(v.offset)||0),next:items.length===512?Math.max(0,Number(v.offset)||0)+512:null,action:'export',launchAttempted:false,message:'Load this playlist in RetroArch on the selected target. Existing playlists and configuration were preserved.'};
 }
 multidisc(v){if(!Array.isArray(v.ids)||v.ids.length<2||v.ids.length>16)throw Error('Select 2 to 16 discs in their intended order');const rows=v.ids.map(id=>this.rows('SELECT * FROM installations WHERE id=?',[id])[0]);if(rows.some(r=>!r)||new Set(rows.map(r=>r.target_id)).size!==1||new Set(rows.map(r=>dirname(r.path))).size!==1)throw Error('Discs must belong to one target and folder');if(new Set(rows.map(r=>r.path)).size!==rows.length)throw Error('Duplicate disc');for(const r of rows){if(!['cue','chd','pbp','ccd','iso'].includes(ext(r.path)))throw Error('Unsupported disc format');this.validate(r.path,r.platform);}const file=dirname(rows[0].path)+'/Raff-'+identifier()+'.m3u';this.fs('playlist',file,rows.map(r=>basename(r.path)).join('\n')+'\n');return{...this.importFile({path:file,platform:rows[0].platform,gameId:rows[0].game_id||undefined}),path:file,discOrder:rows.map(r=>r.path)};}
 remove(id){this.run('DELETE FROM installations WHERE id=?',[id]);return{ok:true,filesDeleted:false};}
 state(){return{profiles:this.profiles(),scans:this.scanStatus(),coverage:parse(this.rows('SELECT value FROM catalog.meta WHERE key=?',['catalog'])[0]?.value,{})};}
}
const api={Library,path,relativeFile,cue,playlist,info,fts};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.RaffLibrary=api;
})(globalThis);
