(function(root){'use strict';
const BT=root.RaffBT||(typeof require==='function'?require('./bittorrent.js'):null),L=root.PS2Library||(typeof require==='function'?require('../shared/core.js'):null);
const terminal=s=>['complete','canceled'].includes(s),uid=()=>{const b=new Uint8Array(8);root.crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');};
class Transfers{
 constructor({sql,client,fs,catalog,clock=()=>Date.now(),legacyActive=()=>0}){Object.assign(this,{sql,client,fs,catalog,clock,legacyActive});this.jobs=[];this.features=[];this.busy=false;this.settings={downloadKiB:0,uploadKiB:64,seedMinutes:0,parallel:2};this.ready=false;}
 rows(s,p=[]){return this.sql(s,p).rows;}
 save(j){const text=JSON.stringify(j);if(text.length>1000000)throw Error('Transfer metadata exceeds database limit');this.sql('INSERT OR REPLACE INTO transfer_jobs(id,state,value,updated_at) VALUES(?,?,?,?)',[j.id,j.state,text,this.clock()]);}
 async init(){this.jobs=this.rows('SELECT id FROM transfer_jobs ORDER BY updated_at DESC LIMIT 128').map(r=>JSON.parse(this.rows('SELECT value FROM transfer_jobs WHERE id=?',[r.id])[0].value));const saved=this.rows("SELECT value FROM setup WHERE key='transfer-settings'")[0];if(saved)Object.assign(this.settings,JSON.parse(saved.value));try{const v=await this.client.rpc('getVersion',[]);this.features=v.enabledFeatures||[];this.ready=true;await this.limits();}catch(e){this.error=e.message;}
 for(const j of this.jobs)if(!terminal(j.state)&&j.state!=='selecting'){if(j.gid)try{await this.client.rpc('forcePause',[j.gid]);}catch{}j.state='paused';j.error='Recovered after restart. Resume to verify and continue.';this.save(j);}}
 async limits(){await this.client.rpc('changeGlobalOption',[{'max-overall-upload-limit':String(this.settings.uploadKiB*1024),'max-overall-download-limit':String(this.settings.downloadKiB*1024)}]);}
 async configure(v){for(const[k,min,max]of[['downloadKiB',0,1048576],['uploadKiB',1,65536],['seedMinutes',0,1440],['parallel',1,4]])if(v[k]!==undefined){if(!Number.isInteger(v[k])||v[k]<min||v[k]>max)throw Error('Invalid bandwidth or seeding setting');this.settings[k]=v[k];}await this.limits();this.sql("INSERT OR REPLACE INTO setup(key,value) VALUES('transfer-settings',?)",[JSON.stringify(this.settings)]);return this.settings;}
 checkCapacity(){if(this.jobs.filter(j=>!terminal(j.state)).length>=64||this.jobs.length>=128||this.jobs.reduce((n,j)=>n+(j.metadata?.length||0),0)>16*1048576)throw Error('Transfer history is full; clear completed transfers first');}
 destination(platform){return platform&&L.PLATFORMS[platform]?L.platformFor(platform).games:'/data/raff/downloads';}
 base(kind,platform){this.checkCapacity();if(platform&&platform!=='files'&&!Object.hasOwn(L.PLATFORMS,platform))throw Error('Unsupported game platform');const id=uid();return{id,kind,platform:platform||'files',mode:'native-ps5',state:'selecting',createdAt:this.clock(),updatedAt:this.clock(),destination:this.destination(platform)+'/Raff-'+id,received:0,total:0,speed:0,uploadSpeed:0,peers:0,seeders:0,attempts:0,error:'',uploadAccepted:false};}
 duplicate(hash){if(this.jobs.some(j=>j.infoHash===hash&&j.state!=='canceled'))throw Error('This torrent is already in Raff');}
 async inspect(v){if(!this.features.includes('BitTorrent'))throw Error('This PS5 aria2 build does not support BitTorrent');let bytes,parsed,j=this.base('torrent',v.platform);
 if(v.magnet){if(v.uploadAccepted!==true)throw Error('Accept the peer-upload notice before contacting torrent peers');const m=BT.magnet(v.magnet);this.duplicate(m.infoHash);Object.assign(j,{name:'Magnet metadata',infoHash:m.infoHash,magnet:m.uri,state:'metadata-queued',uploadAccepted:true,lastProgress:this.clock()});await this.client.ensureDir(j.destination);this.jobs.unshift(j);this.save(j);return this.detail(j.id);}
 if(v.path){if(!/^\/data\/raff\/imports\/[^/]+\.torrent$/i.test(v.path))throw Error('Put torrent files in /data/raff/imports');const stat=this.fs('stat',v.path);if(!stat||stat.type!=='file'||stat.size>BT.MAX)throw Error('Torrent metadata limit is 512 KiB');bytes=new Uint8Array(this.fs('slice',v.path,{offset:0,length:stat.size}));}else bytes=BT.unbase64(v.torrent);
 parsed=BT.parse(bytes);this.duplicate(parsed.infoHash);Object.assign(j,parsed,{metadata:BT.base64(bytes),selected:[],total:parsed.total});this.jobs.unshift(j);try{this.save(j);}catch(e){this.jobs.shift();throw e;}return this.detail(j.id);}
 options(j,metadata=false){return{dir:j.destination,gid:j.requestedGid||j.id,'allow-overwrite':'false','auto-file-renaming':'false','file-allocation':'none',continue:'true','check-integrity':'true','max-tries':'3','retry-wait':'10','connect-timeout':'15',timeout:'30','bt-stop-timeout':'120','bt-max-peers':'40','max-upload-limit':String(this.settings.uploadKiB*1024),'max-download-limit':String(this.settings.downloadKiB*1024),'seed-time':String(metadata?0:this.settings.seedMinutes),'seed-ratio':metadata||!this.settings.seedMinutes?'0':'1.0','bt-seed-unverified':'false','bt-remove-unselected-file':'false','bt-save-metadata':'true','bt-metadata-only':metadata?'true':'false','pause-metadata':'true','follow-torrent':'false','select-file':metadata?'':(j.selected||[]).join(',')};}
 async reserve(j){await this.client.ensureDir(j.destination);this.fs('stat',j.destination);const bytes=j.kind==='torrent'?j.files.filter(f=>j.selected.includes(f.index)).reduce((n,f)=>n+f.length,0):j.total;const reserved=this.jobs.filter(x=>x.id!==j.id&&!terminal(x.state)&&x.state!=='selecting').reduce((n,x)=>n+Math.max(0,(x.total||0)-(x.received||0)),0);const required=Math.max(0,bytes-(j.received||0))+(j.pieceLength||0)*2+128*1048576+reserved;if(await this.client.available(j.destination)<required)throw Error('Not enough free storage; partial files are kept');j.total=bytes;}
 find(id){const j=this.jobs.find(j=>j.id===id);if(!j)throw Error('Unknown transfer');return j;}
 async start(id,v={}){const j=this.find(id);if(!['selecting','paused','stalled','error'].includes(j.state))throw Error('Transfer is not ready');if(j.kind==='torrent'){if(v.uploadAccepted!==true&&j.uploadAccepted!==true)throw Error('Torrent downloads also upload pieces to peers');if(!j.metadata)throw Error('Torrent metadata is not available yet; retry metadata first');if(v.selected){if(!Array.isArray(v.selected)||!v.selected.length||new Set(v.selected).size!==v.selected.length||v.selected.some(n=>!Number.isInteger(n)||!j.files.some(f=>f.index===n&&!f.padding)))throw Error('Select valid torrent files');if(j.received>0&&JSON.stringify(v.selected)!==JSON.stringify(j.selected))throw Error('File selection is fixed after downloading starts');j.selected=v.selected;}if(!j.selected?.length)throw Error('Select at least one file');j.uploadAccepted=true;}await this.reserve(j);j.state='queued';j.error='';j.attempts=0;this.save(j);return this.detail(id);}
 async addRelease(id,v={}){const r=this.catalog.releases.find(x=>x.id===id);if(!r||r.permission?.status!=='verified'||!r.permission.evidence||!r.license)throw Error('No verified distribution permission for this release');if(!r.host||!['ps5','windows','linux','macos','ps1','ps2','switch','data'].includes(r.host))throw Error('Unsupported release host');if(this.jobs.some(j=>j.releaseId===id&&j.state!=='canceled'))throw Error('Release already queued or downloaded');if(r.magnet){const d=await this.inspect({magnet:r.magnet,platform:r.platform,uploadAccepted:v.uploadAccepted===true});const j=this.find(d.id);j.releaseId=id;this.save(j);return d;}BT.url(r.url);if(!Number.isSafeInteger(r.size)||r.size<1||!/^sha-256=[a-f0-9]{64}$/.test(r.checksum))throw Error('Release requires a verified size and SHA-256');const j=this.base('https',r.platform);Object.assign(j,{name:r.title||r.filename,releaseId:id,host:r.host,url:r.url,filename:BT.segment(r.filename),checksum:r.checksum,total:r.size,state:'queued',selected:[1],files:[{index:1,path:r.filename,length:r.size}],license:r.license});await this.reserve(j);this.jobs.unshift(j);this.save(j);return this.detail(j.id);}
 async launch(j){const options=this.options(j);if(j.kind==='torrent'){BT.parse(BT.unbase64(j.metadata));j.gid=await this.client.rpc('addTorrent',[j.metadata,[],options]);}else{delete options['select-file'];options.out=j.filename;options.checksum=j.checksum;options.split='4';options['max-connection-per-server']='4';j.gid=await this.client.rpc('addUri',[[j.url],options]);}j.state='downloading';j.lastProgress=this.clock();j.lastSave=this.clock();this.save(j);}
 async action(id,action){const j=this.find(id);if(action==='cancel'){if(j.gid)try{await this.client.rpc('forceRemove',[j.gid]);}catch{}j.state='canceled';j.speed=0;j.uploadSpeed=0;j.error='Partial files kept at '+j.destination;this.save(j);return;}
 if(terminal(j.state))throw Error('Transfer is already complete or canceled');if(action==='pause'){if(j.gid)try{await this.client.rpc('forcePause',[j.gid]);}catch{}j.state='paused';j.speed=0;j.uploadSpeed=0;this.save(j);return;}
 if(action==='resume'){if(j.kind==='torrent'&&!j.metadata){await this.restartMetadata(j);return;}await this.start(id,{uploadAccepted:j.uploadAccepted});return;}
 if(action==='fallback'){const r=this.catalog.releases.find(x=>x.id===j.releaseId);if(!r?.fallbackRelease)throw Error('No authorized HTTPS fallback');return this.addRelease(r.fallbackRelease);}throw Error('Unsupported transfer action');}
 async restartMetadata(j){if(!j.magnet||!j.uploadAccepted)throw Error('Metadata cannot be retried');if(j.gid){try{await this.client.rpc('forceRemove',[j.gid]);}catch{}try{await this.client.rpc('removeDownloadResult',[j.gid]);}catch{}}delete j.gid;j.requestedGid=uid();j.state='metadata-queued';j.error='';j.lastProgress=this.clock();this.save(j);}
 async metadataDone(j){const path=j.destination+'/'+j.infoHash+'.torrent',stat=this.fs('stat',path);if(!stat||stat.type!=='file'||stat.size>BT.MAX)throw Error('Metadata file is missing or too large');const bytes=new Uint8Array(this.fs('slice',path,{offset:0,length:stat.size})),p=BT.parse(bytes);if(p.infoHash!==j.infoHash)throw Error('Magnet metadata hash mismatch');await this.client.rpc('removeDownloadResult',[j.gid]);delete j.gid;Object.assign(j,p,{metadata:BT.base64(bytes),selected:[],total:p.total,state:'selecting',received:0,speed:0});this.save(j);}
 async tick(){if(this.busy)return;this.busy=true;try{if(!this.ready){const v=await this.client.rpc('getVersion',[]);this.features=v.enabledFeatures||[];this.ready=true;await this.limits();}let running=this.jobs.filter(j=>['downloading','metadata','seeding'].includes(j.state)).length;
 for(const j of this.jobs){if(j.catalogGame){running+=await this.tickGame(j,running<this.settings.parallel&&running+this.legacyActive()<4);continue;}if(j.state==='metadata-queued'&&running<this.settings.parallel&&running+this.legacyActive()<4){running++;try{await this.client.ensureDir(j.destination);this.fs('stat',j.destination);j.gid=await this.client.rpc('addUri',[[j.magnet],this.options(j,true)]);j.state='metadata';j.lastProgress=this.clock();}catch(e){j.state='error';j.error=e.message;}this.save(j);continue;}if(j.state==='queued'&&running<this.settings.parallel&&running+this.legacyActive()<4){running++;try{await this.reserve(j);if(j.gid){try{await this.client.rpc('changeOption',[j.gid,{'max-upload-limit':String(this.settings.uploadKiB*1024),'max-download-limit':String(this.settings.downloadKiB*1024)}]);await this.client.rpc('unpause',[j.gid]);j.state='downloading';j.lastProgress=this.clock();this.save(j);}catch{try{await this.client.rpc('removeDownloadResult',[j.gid]);}catch{}delete j.gid;j.requestedGid=uid();await this.launch(j);}}else await this.launch(j);}catch(e){j.state='error';j.error=e.message;this.save(j);}continue;}
 if(!['downloading','metadata','seeding'].includes(j.state)||!j.gid)continue;try{const s=await this.client.rpc('tellStatus',[j.gid]);j.peers=+s.connections||0;j.seeders=+s.numSeeders||0;j.uploadSpeed=+s.uploadSpeed||0;j.uploaded=+s.uploadLength||0;j.speed=+s.downloadSpeed||0;
 const received=j.kind==='torrent'&&j.metadata?(BT.completed(j.files,j.selected,j.pieceLength,s.bitfield)??(s.files||[]).filter(f=>f.selected==='true').reduce((n,f)=>n+Math.min(+f.length,+f.completedLength),0)):+s.completedLength||0;if(received>j.received){j.lastProgress=this.clock();j.received=received;}j.eta=j.speed>0&&j.total>received?Math.ceil((j.total-received)/j.speed):null;
 if(j.state==='metadata'&&s.status==='complete'){await this.metadataDone(j);continue;}
 if(s.status==='error'){if(j.attempts<2&&['1','2','6','7','19','20','22','23','24','29'].includes(s.errorCode)){j.attempts++;j.state='retrying';j.retryAt=this.clock()+j.attempts*10000;j.error=s.errorMessage||'Connection interrupted';}else{j.state='error';j.error=(s.errorCode==='32'?'Integrity check failed. ':'')+(s.errorMessage||'aria2 error '+s.errorCode);}this.save(j);continue;}
 if(s.status==='complete'||s.seeder==='true'){if(received<j.total)throw Error('Downloaded files are incomplete');for(const f of j.files.filter(f=>j.selected.includes(f.index))){const actual=this.fs('stat',j.destination+'/'+f.path);if(!actual||actual.type!=='file'||actual.size!==f.length)throw Error('Downloaded file size does not match metadata');}if(j.kind==='https'&&+s.totalLength!==j.total)throw Error('Publisher file size does not match');j.received=j.total;j.integrity=j.kind==='torrent'?'torrent-pieces':'sha256';j.state=s.status==='complete'?'complete':'seeding';if(j.state==='complete')j.completedAt=this.clock();this.save(j);continue;}
 if(s.status==='paused'){j.state='paused';this.save(j);continue;}
 if(this.clock()-j.lastProgress>120000&&j.state!=='seeding'){await this.client.rpc('forcePause',[j.gid]);j.state='stalled';j.error='No progress for two minutes. No usable peers or blocked connection; resume to retry.';this.save(j);continue;}
 if(this.clock()-(j.lastSave||0)>5000){j.lastSave=this.clock();this.save(j);}
 }catch(e){if(j.gid)try{await this.client.rpc('forcePause',[j.gid]);}catch{}j.state='error';j.error=e.message;this.save(j);}}
 for(const j of this.jobs.filter(j=>j.state==='retrying'&&this.clock()>=j.retryAt)){if(j.kind==='torrent'&&!j.metadata)await this.restartMetadata(j);else{j.state='queued';this.save(j);}}
 }catch(e){this.error=e.message;this.ready=false;}finally{this.busy=false;}}
 detail(id,offset=0){const j=this.find(id);return{...this.summary(j),files:(j.files||[]).slice(Math.max(0,offset),Math.max(0,offset)+128).map(f=>({...f,selected:j.selected?.includes(f.index)})),fileCount:j.files?.length||0,uploadNotice:'BitTorrent shares downloaded pieces with peers. Your IP is visible. Upload '+this.settings.uploadKiB+' KiB/s; seed after completion '+this.settings.seedMinutes+' minutes.',host:j.host||j.platform,infoHash:j.infoHash};}
 summary(j){return{id:j.id,name:j.name,title:j.name,key:'transfer:'+j.id,platform:j.platform,mode:'native-ps5',kind:j.kind,state:j.state,phase:j.state,paused:j.state==='paused',destination:j.destination,received:j.received,total:j.total,speed:j.speed,uploadSpeed:j.uploadSpeed,uploaded:j.uploaded||0,eta:j.eta??null,peers:j.peers,seeders:j.seeders,progress:j.total?Math.min(1,j.received/j.total):0,error:j.error,errorKind:j.error?'networkerror':'',errorDetail:j.error,integrity:j.integrity||'pending',completedAt:j.completedAt,releaseId:j.releaseId,uploadAccepted:j.uploadAccepted,host:j.host||j.platform};}
 state(){return{ready:this.ready,mode:'native-ps5',bitTorrent:this.features.includes('BitTorrent'),settings:this.settings,error:this.error||'',jobs:this.jobs.map(j=>this.summary(j))};}
 clear(){for(const j of this.jobs.filter(j=>terminal(j.state)))this.sql('DELETE FROM transfer_jobs WHERE id=?',[j.id]);this.jobs=this.jobs.filter(j=>!terminal(j.state));return{ok:true,filesDeleted:false};}
}
const api={Transfers};if(typeof module!=='undefined')module.exports=api;else root.RaffTransfers=api;
})(globalThis);
