import{tc,buildEnv}from'./toolchain.mjs';
import {spawnSync} from 'node:child_process';import{readFile,writeFile,readdir,mkdir,stat}from'node:fs/promises';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),base=resolve(root,'../..'),work=tc.work,out=resolve(work,'service-build');await mkdir(out,{recursive:true});
const zig=tc.zig,sdk=tc.sdk,qjs=tc.quickjs;
const env=buildEnv;
function run(a){const r=spawnSync(zig,a,{stdio:'inherit',env});if(r.status!==0)process.exit(r.status||1);}
const scripts=[resolve(root,'service/polyfills.js'),resolve(root,'shared/core.js'),resolve(root,'shared/identity.js'),resolve(root,'service/packages.js'),resolve(root,'service/transport.js'),resolve(root,'service/queue.js'),resolve(root,'service/dependencies.js'),resolve(root,'service/library.js'),resolve(root,'service/media.js'),resolve(root,'service/psxs5.js'),...['sources','bittorrent','hub','transfers','game-transfers','updates','main'].map(n=>resolve(root,'service/'+n+'.js'))];
const bundle=(await Promise.all(scripts.map(p=>readFile(p,'utf8')))).join('\n;\n');
await writeFile(resolve(out,'bundle.js'),bundle);
let assembly='.section .rodata\n';for(const[name,path]of Object.entries({js_data:resolve(out,'bundle.js'),catalog_data:resolve(root,'assets/catalog-full.json')})){let b=await readFile(path);assembly+=`# ${createHash('sha256').update(b).digest('hex')}\n.global ${name}\n.global ${name}_end\n${name}:\n.incbin "${path.replaceAll('\\','/')}"\n${name}_end:\n.byte 0\n`; }await writeFile(resolve(out,'assets.S'),assembly);
const sources=['quickjs.c','dtoa.c','libregexp.c','libunicode.c','cutils.c'].map(n=>resolve(qjs,n));sources.push(resolve(root,'third_party/sqlite/sqlite3.c'),resolve(root,'service/database.c'),resolve(root,'service/filesystem.c'),resolve(root,'service/host.c'),resolve(root,'service/updater.c'),resolve(root,'service/bootstrap.c'),resolve(out,'assets.S'));const objects=[];
for(const s of sources){const o=resolve(out,s.split(/[\\/]/).pop()+'.o');objects.push(o);if((await stat(o).catch(()=>({mtimeMs:0}))).mtimeMs>(await stat(s)).mtimeMs)continue;console.log('Compile service',s.split(/[\\/]/).pop());run(['cc','-target','x86_64-freebsd','-D__SCE__','-D_GNU_SOURCE','-DSQLITE_ENABLE_FTS5','-DSQLITE_THREADSAFE=0','-DSQLITE_OMIT_LOAD_EXTENSION','-DSQLITE_OMIT_WAL','-DSQLITE_MAX_MMAP_SIZE=0','-DSQLITE_DEFAULT_CACHE_SIZE=-4096','-DCONFIG_VERSION="2026-10-05"','-Wno-unreachable-code-generic-assoc','-O2','-fPIC','-fno-stack-protector','-fno-plt','-femulated-tls','-nostdinc','-I',resolve(sdk,'target/include'),'-isystem',resolve(dirname(zig),'lib/include'),'-I',qjs,'-I',resolve(tc.pacbrew,'include'),'-c',s,'-o',o]);}
run(['ld.lld','-m','elf_x86_64','-pie','--eh-frame-hdr','-z','max-page-size=0x4000','--hash-style=gnu','-T',resolve(sdk,'ldscripts/elf_x86_64.x'),...objects,'--start-group',...['crypto'].map(n=>resolve(tc.pacbrew,'lib/lib'+n+'.a')),'--end-group',resolve(sdk,'target/lib/crt1.o'),'-L',resolve(sdk,'target/lib'),'-lc','-lkernel_web','-lSceLibcInternal','-lSceNet','-o',resolve(root,'raff-service.elf')]);console.log('Built Raff service');
