// Admin-only, streaming torrent creation. Never uploads or starts seeding.
import fs from 'node:fs/promises';import path from 'node:path';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import BT from'../service/bittorrent.js';import hub from'../service/hub.js';
export function encode(v){if(Buffer.isBuffer(v)||v instanceof Uint8Array)return Buffer.concat([Buffer.from(v.length+':'),Buffer.from(v)]);if(typeof v==='string')return encode(Buffer.from(v));if(Number.isSafeInteger(v))return Buffer.from('i'+v+'e');if(Array.isArray(v))return Buffer.concat([Buffer.from('l'),...v.map(encode),Buffer.from('e')]);if(v&&typeof v==='object')return Buffer.concat([Buffer.from('d'),...Object.keys(v).sort().flatMap(k=>[encode(k),encode(v[k])]),Buffer.from('e')]);throw Error('Invalid bencode value');}
export async function createTorrent(input,{trackers=[],webSeeds=[],pieceLength=262144,license,permission,name}={}){
 if(!license||!permission)throw Error('Document --license and --permission before creating distribution metadata');BT.url(permission);trackers.forEach(t=>BT.url(t,true));webSeeds.forEach(t=>BT.url(t));
 const root=path.resolve(input),stat=await fs.lstat(root);if(stat.isSymbolicLink())throw Error('Symlinks are forbidden');name=BT.segment(name||path.basename(root));const files=[];
 async function walk(full,relative=[]){const s=await fs.lstat(full);if(s.isSymbolicLink())throw Error('Symlinks are forbidden');if(s.isDirectory()){for(const n of(await fs.readdir(full)).sort())await walk(path.join(full,n),[...relative,BT.segment(n)]);}else if(s.isFile()){if(files.length>=2048)throw Error('File limit is 2048');files.push({full,path:relative,length:s.size});}else throw Error('Unsupported file type');}
 await walk(root);if(!files.length)throw Error('Empty input');if(!Number.isSafeInteger(pieceLength)||pieceLength<16384||pieceLength>16777216||(pieceLength&(pieceLength-1)))throw Error('Invalid piece length');
 const pieces=[],buffer=Buffer.alloc(Math.min(pieceLength,1048576));let pending=0,sha=createHash('sha1');
 for(const file of files){const f=await fs.open(file.full,'r');try{let at=0;while(at<file.length){const{bytesRead}=await f.read(buffer,0,Math.min(buffer.length,pieceLength-pending,file.length-at),at);if(!bytesRead)throw Error('File changed while reading');sha.update(buffer.subarray(0,bytesRead));pending+=bytesRead;at+=bytesRead;if(pending===pieceLength){pieces.push(sha.digest());sha=createHash('sha1');pending=0;}}if((await f.stat()).size!==file.length)throw Error('File size changed');}finally{await f.close();}}
 if(pending)pieces.push(sha.digest());const info={name,'piece length':pieceLength,pieces:Buffer.concat(pieces)};if(stat.isDirectory())info.files=files.map(({path,length})=>({length,path}));else info.length=stat.size;
 const metadata={info,'created by':'RAFF torrent-admin','creation date':Math.floor(Date.now()/1000),comment:'License: '+license+'; permission: '+permission};if(trackers.length){metadata.announce=trackers[0];metadata['announce-list']=trackers.map(x=>[x]);}if(webSeeds.length)metadata['url-list']=webSeeds;
 const bytes=encode(metadata),parsed=BT.parse(bytes),magnet='magnet:?xt=urn:btih:'+parsed.infoHash+'&dn='+encodeURIComponent(name)+trackers.map(t=>'&tr='+encodeURIComponent(t)).join('');return{bytes,magnet,parsed};
}
async function cli(){const[command,input,output,...rest]=process.argv.slice(2);if(command==='validate'){hub.validate(JSON.parse(await fs.readFile(input,'utf8')));console.log('Catalog validated; permission evidence still requires human review.');return;}
 if(command!=='create'||!input||!output)throw Error('Usage: node torrent-admin.mjs create INPUT OUTPUT.torrent --license SPDX --permission https://evidence [--tracker URL] [--webseed HTTPS-URL] | validate hub.json');
 const options={trackers:[],webSeeds:[]};for(let n=0;n<rest.length;n+=2){const k=rest[n],v=rest[n+1];if(!v)throw Error('Missing option value');if(k==='--tracker')options.trackers.push(v);else if(k==='--webseed')options.webSeeds.push(v);else if(k==='--license')options.license=v;else if(k==='--permission')options.permission=v;else if(k==='--piece-length')options.pieceLength=Number(v);else throw Error('Unknown option '+k);}
 const result=await createTorrent(input,options);await fs.writeFile(output,result.bytes,{flag:'wx'});await fs.writeFile(output+'.magnet',result.magnet+'\n',{flag:'wx'});await fs.writeFile(output+'.json',JSON.stringify({schema:1,name:result.parsed.name,infoHash:result.parsed.infoHash,total:result.parsed.total,files:result.parsed.files,license:options.license,permission:{status:'needs-review',evidence:options.permission},seeding:'Not started. Keep an authorized complete seed online; see docs/TORRENTS.md.'},null,2),{flag:'wx'});console.log(JSON.stringify({torrent:path.resolve(output),magnet:result.magnet,files:result.parsed.files.length,total:result.parsed.total}));
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))cli().catch(e=>{console.error(e.message);process.exitCode=1;});
